import React from "react";
import ReinstatementFunctional from "./reinstatementfunctional";
import {
  BIND_REINSTATE,
  RATE_ENDORSEMENT,
  REVERT_TRANSACTION,
  TRIGGER_NOTIFICATION,
  UPDATE_POLICY,
} from "./utilities/gqlSchema";
// import { save, updatePolicyStatus, triggerNotification } from "@cogitate/ui-utils-core-test";

const uiDataModel = {
  id: "d681b77e-a5eb-4e92-ac1c-bbb734028148",
  AccountId: "UW",
  QuoteNumber: "04252023175922",
  IsPolicyBind: true,
  IsInForce: false,
  IsRenewed: false,
  PolicyNumber: "GAPA006301296",
  PayMode: "",
  PolicyTerm: {
    Value: 6,
    ValueType: "Months",
  },
  EffectiveDate: "2023-04-26",
  ExpirationDate: "2023-10-26",
  InceptionTime: "01:00 PM",
  SignatureType: "",
  BindDate: "2023-04-26",
  QuoteDate: "2023-04-26",
  QuoteExpDate: "",
  PolicyStatus: "Policy Cancelled",
  CurrentVersion: "2",
  CurrentVersionEffectiveFrom: "2023-06-06",
  RenewalTerm: 0,
  RenewalQuoteID: 0,
  IsOOS: null,
  PolicyRiskAttributes: {
    FirstName: "ALICE",
    MiddleName: "",
    LastName: "BURNS",
    Communications: [
      {
        Type: "PhNo",
        SubType: "Primary",
        Value: "2332232323",
        Status: "Active",
        AcceptText: true,
      },
      {
        Type: "Email",
        SubType: "Primary",
        Value: "asingh2@Cogitate.us",
        Status: "Active",
        AcceptText: null,
      },
    ],
    EstimatedBalanceAfterCancel: 0,
    BillingAccountNumber: 0,
    CurrentPolicyBalance: 0,
    DropboxSignatureRequestID: "",
    CancellationCount: 0,
    ReinstatementCount: 0,
    EndorsementCount: 0,
    InstallmentDueDate: null,
    CurrentInstallmentAmount: null,
  },
  Attributes: {
    AppSource: "POS",
    Carrier: "IH",
    Client: null,
    Coverholder: "IH",
    Lob: "PA",
    State: "GA",
    Product: "GAPA",
    RaterVersion: "1.0.0.8",
    IsBridge: false,
    IsInEligible: true,
    IsNonOwnerPolicy: false,
    FullCoverage: true,
    TotalViolationPoints: 0,
    IsTestPolicy: true,
    RenewalConfigurations: {
      BeforeForAgent: {
        Value: null,
        ValueType: null,
      },
      AfterForAgent: {
        Value: null,
        ValueType: null,
      },
      BeforeForUnderwriter: {
        Value: null,
        ValueType: null,
      },
      AfterForUnderwriter: {
        Value: null,
        ValueType: null,
      },
    },
    QuoteValidity: {
      Value: null,
      ValueType: null,
    },
  },
  PolicyStatusHistory: [
    {
      OldStatus: "Policy In Force-Bind",
      NewStatus: "Endorsement Initiated",
      ChangedBy: "12911",
      ChangedDate: "2023-06-06",
    },
    {
      OldStatus: "Endorsement Initiated",
      NewStatus: "Cancellation Request Pending Approval",
      ChangedBy: "12911",
      ChangedDate: "2023-06-08",
    },
    {
      OldStatus: "Cancellation Request Pending Approval",
      NewStatus: "Policy Cancelled",
      ChangedBy: "001",
      ChangedDate: "2023-07-13",
    },
  ],
  Transaction: {
    Number: 1,
    Date: "2023-04-26",
    EffectiveDate: "2023-06-08",
    EffectiveTime: "12:01 AM",
    Type: "Cancellation",
    Status: "Committed",
    RequestedBy: "",
    RequestedById: "",
    IsOutOfSequence: false,
    PremiumType: "ProRate",
    PolicyVersion: "",
    FileType: "",
    FileName: "",
    File: "",
    Remarks: "",
    HoldRemarks: "",
    RejectRemarks: "",
    Reason: "Double Coverage",
    ReasonId: "",
    MEP: 0,
    SCR: 0,
    Verification: {
      IsInsuredESignVerified: false,
      IsAgentESignVerified: false,
      IsEmailVerified: false,
      IsOTPVerified: false,
      InsuredOTP: "",
    },
    TransactionStatusHistory: [
      {
        OldStatus: "",
        NewStatus: "",
        ChangedBy: "",
        ChangedDate: "",
      },
    ],
    RenewalOffers: {
      RenewalOfferId: "",
      CurrentPremium: 0,
      RenewalPremium: 0,
      IsUpdateRenewalPremium: true,
      RenewalOfferFlags: {
        CreatedOn: "",
        UpdatedOn: "",
        CreatedBy: "",
        UpdatedBy: "",
        EmailSentFlag: false,
      },
    },
  },
  AgentCommission: {
    Value: "10",
    ValueType: "Percent",
  },
  Agency: {
    Client: "SGIH",
    Code: "104349",
    Name: "Whit Blanchard Insurance Group",
    Status: "Active",
    Reference: ["12911", "13624"],
    Products: ["GAPA"],
    Address: {
      Number: 1,
      AddressType: "M",
      IsManual: null,
      Description: "Mailing Address",
      AddressLine1: "1901 Walton Way",
      AddressLine2: "",
      AptSuite: "",
      City: "Augusta",
      County: "US",
      CountyCode: "",
      State: "GA",
      PoBox: "",
      Postalcode: "30904",
      FormattedAddress: "",
      UnFormattedAddress: "",
      AdministrationArea1: "",
      AdministrationArea2: "",
      Locality: "",
      Lat: "",
      Long: "",
      Name: "",
      Premise: "",
      Status: "",
      Territory: "",
      Business: "",
      PlaceId: "",
      AptSuiteLot: "Apt",
      Street: "",
      StreetName: "",
    },
    Communications: [
      {
        Type: "PhNo",
        SubType: "Primary",
        Value: "992-456-7898",
        Status: "Active",
        AcceptText: null,
      },
      {
        Type: "Email",
        SubType: "Primary",
        Value: "ashleyadair@whitbinsurance.com",
        Status: "Active",
        AcceptText: null,
      },
    ],
  },
  Agent: {
    Client: "SGIH",
    Code: "12911",
    Name: "Kaitlin Hass",
    Status: "Active",
    Reference: ["104349"],
    Products: ["GAPA"],
    Address: {
      Number: 1,
      AddressType: "M",
      IsManual: null,
      Description: "",
      AddressLine1: "PO Box 1219",
      AddressLine2: "",
      AptSuite: "",
      City: "Hinesville",
      County: "Liberty",
      CountyCode: "",
      State: "GA",
      PoBox: "",
      Postalcode: "31310",
      FormattedAddress: "",
      UnFormattedAddress: "",
      AdministrationArea1: "",
      AdministrationArea2: "",
      Locality: "",
      Lat: "",
      Long: "",
      Name: "",
      Premise: "",
      Status: "",
      Territory: "",
      Business: "",
      PlaceId: "",
      AptSuiteLot: "Apt",
      Street: "",
      StreetName: "",
    },
    Communications: [
      {
        Type: "PhNo",
        SubType: "Primary",
        Value: "923-656-7891",
        Status: "Active",
        AcceptText: null,
      },
      {
        Type: "Email",
        SubType: "Primary",
        Value: "msingh@cogitate.us",
        Status: "Active",
        AcceptText: null,
      },
    ],
  },
  UnderWriter: {
    Client: "SGIH",
    Code: "001",
    Name: "test UW",
    Status: "Active",
    Reference: ["101001"],
    Products: ["1", "2", "3"],
    UWAttributes: {
      UWOffice: "Rosewell",
      ContractNumber: "ACV124",
      AccountExecCode: "bclark",
    },
  },
  PriorInsurances: [
    {
      IsCurrentlyInsured: false,
      CompanyName: "Other",
      OtherCompanyName: "xyz insurance",
      EffectiveDate: "2022-08-18",
      ExpirationDate: "2023-08-18",
      Premium: 6545,
      Status: "Active",
    },
  ],
  Premium: {
    BasicPremium: null,
    Surcharge: 0,
    Discount: 0,
    MinPremium: null,
    EffectivePremium: 0,
    AnnualPremium: 0,
    EffectivePremiumWithFeesAndTaxes: null,
    AnnualPremiumWithFeesAndTaxes: null,
  },
  InsuredAccount: {
    Type: "Primary",
    CreationDate: "",
    Suffix: "",
    UserName: "",
    FirstName: "ALICE",
    MiddleName: "",
    LastName: "BURNS",
    DisplayName: "",
    DOB: "2000-11-16",
    BankDetails: {
      AccountName: "",
      BankName: "",
      BranchName: "",
      AccountType: "",
      RoutingNo: "",
    },
    Address: {
      Number: 1,
      AddressType: "Primary",
      IsManual: false,
      Description: "Mailing Address",
      AddressLine1: "1345 South Ga Avenue",
      AddressLine2: "",
      AptSuite: "",
      City: "Bremen",
      County: "Haralson County",
      CountyCode: "",
      State: "GA",
      PoBox: "",
      Postalcode: "30110",
      FormattedAddress: "1345 Old Carrollton Road",
      UnFormattedAddress: "1345 South Ga Avenue, Bremen, GA, USA",
      AdministrationArea1: "",
      AdministrationArea2: "",
      Locality: "",
      Lat: "",
      Long: "",
      Name: "",
      Premise: "",
      Status: "",
      Territory: "",
      Business: "",
      PlaceId:
        "EiUxMzQ1IFNvdXRoIEdhIEF2ZW51ZSwgQnJlbWVuLCBHQSwgVVNBIjESLwoUChIJxV-khQXYiogRvepDM0izozYQwQoqFAoSCSVwAd4O2IqIEceomtvTuXsV",
      AptSuiteLot: "Apt",
      Street: "1345 Old Carrollton Road",
      StreetName: "1345 Old Carrollton Road",
    },
    Communications: [
      {
        Type: "PhNo",
        SubType: "Primary",
        Value: "2332232323",
        Status: "Active",
        AcceptText: true,
      },
      {
        Type: "Email",
        SubType: "Primary",
        Value: "asingh2@Cogitate.us",
        Status: "Active",
        AcceptText: null,
      },
    ],
    BusinessInfo: {
      BusinessType: "",
      YearsInBusiness: 4.5,
      IncorporationAge: "",
      BusinessName: "Sample Business Name",
      DisplayName: "",
      RegistrationNumber: "",
      BusinessStruct: "",
      SpecialRisk: "",
      NoOfOwners: 1,
      FullTimeEmployees: 22,
      PartTimeEmployees: 12,
      Website: "",
      IndustryType: "",
      BusinessDecsription: "",
      AnnualRevenue: 9456456,
      NumberOFLocations: 2,
      Locations: [
        {
          NickName: "",
          LocationNumber: 1,
          IsValid: true,
          Status: "Active",
          Type: "Primary",
        },
      ],
    },
    IsAuthorizeForReports: "true",
    IsAuthorizationforConsumerRatingInformation: "",
    IsAuthorizeForCreditScore: "true",
    CreditScore: {
      Score: "998",
      ScoreDescription: "",
      StatusCode: "",
      Message: "Requested – Not Received",
      NeedApiCall: false,
    },
  },
  JointPolicyHolders: [
    {
      FirstName: "",
      MiddleName: "",
      LastName: "",
      DateOfBirth: "",
      InsuredType: "",
      Age: {
        Value: "",
        ValueType: "",
      },
      Occupation: "",
      IsHighProfile: false,
      IsAddressSameAsRisk: true,
      Address: {
        Number: 1,
        AddressType: "",
        IsManual: null,
        Description: "Mailing Address",
        AddressLine1: "",
        AddressLine2: "",
        AptSuite: "",
        City: "",
        County: "",
        CountyCode: "",
        State: "GA",
        PoBox: "",
        Postalcode: "",
        FormattedAddress: "",
        UnFormattedAddress: "",
        AdministrationArea1: "",
        AdministrationArea2: "",
        Locality: "",
        Lat: "",
        Long: "",
        Name: "",
        Premise: "",
        Status: "",
        Territory: "",
        Business: "",
        PlaceId: "",
        AptSuiteLot: "Apt",
        Street: "",
        StreetName: "",
      },
      Communications: [
        {
          Type: "PhNo",
          SubType: "Primary",
          Value: "",
          Status: "Active",
          AcceptText: null,
        },
        {
          Type: "Email",
          SubType: "Primary",
          Value: "",
          Status: "Active",
          AcceptText: null,
        },
      ],
    },
  ],
  Audit: {
    CreatedBy: "ih.testga2",
    CreatedOn: "2023-04-25T12:29:22.341Z",
    DeletedOn: null,
    LastUpdatedBy: "ih.william",
    LastUpdatedOn: "2023-07-13T12:19:40.186Z",
  },
  ExternalRefrences: [
    {
      ReferenceNumber: "0246879",
      ReferenceTarget: "AIM_QuoteID",
      Status: "Active",
    },
  ],
  Claims: [
    {
      Status: "Active",
      ClaimSequence: 1,
      IsUnrepairedDamage: true,
      DateofLoss: "2022-09-07",
      PaidAmount: 5000,
      ReserveAmount: 5000,
      IncidentType: "Flood",
      CoverageType: "HO",
      ClaimantName: "Ben Johns",
      UnitId: 1,
      Remark: "Flood Claim ",
    },
  ],
  Forms: [
    {
      Status: "",
      FormName: "SG1002",
      FormDesc: "Endorsement Declarations",
      Sequence: 1,
      FormType: "Dynamic",
      Template: "gnfolwkc4ji",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH003",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1021",
      FormDesc: "Driver Exclusion Request",
      Sequence: 2,
      FormType: "Dynamic",
      Template: "qlxytaa113q",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH063",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1020",
      FormDesc: "Policy Change Endorsement",
      Sequence: 3,
      FormType: "Dynamic",
      Template: "ub5puzc2iz1",
      IsMandatory: true,
      IsChecked: null,
      AcordCode: "IH009",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1030",
      FormDesc: "Auto ID Cards",
      Sequence: 4,
      FormType: "Dynamic",
      Template: "bxxckzizzrm",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH060",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1031",
      FormDesc: "Good Student Discount",
      Sequence: 5,
      FormType: "Dynamic",
      Template: "pk3ouljdp2i",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH013",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1032",
      FormDesc: "Statement of Physical Condition",
      Sequence: 6,
      FormType: "Dynamic",
      Template: "5hx4qrcfsii",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH061",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1036",
      FormDesc: "Inspection Report",
      Sequence: 7,
      FormType: "Dynamic",
      Template: "qqwgq1aunri",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH064",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1044",
      FormDesc: "Request for FFH/Med Pay Coverage",
      Sequence: 8,
      FormType: "Dynamic",
      Template: "pgw4zazjtde",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH062",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1070",
      FormDesc: "Signed Uninsured Motorist Form",
      Sequence: 9,
      FormType: "Dynamic",
      Template: "j2v22d55vtc",
      IsMandatory: true,
      IsChecked: null,
      AcordCode: "IH027",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG5107",
      FormDesc: "Uninsured Motorist Informational Notice",
      Sequence: 10,
      FormType: "Static",
      Template: "pgfdhsavg4j",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH035",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "SG1074",
      FormDesc: "Punitive Damages Inclusion",
      Sequence: 11,
      FormType: "Dynamic",
      Template: "ktp11qxj44o",
      IsMandatory: false,
      IsChecked: null,
      AcordCode: "IH047",
      File: "",
      Dmspath: "",
    },
    {
      Status: "",
      FormName: "EndorsementSummary",
      FormDesc: "Policy Summary After Endorsement",
      Sequence: 12,
      FormType: "Dynamic",
      Template: "uzefdfsi4cj",
      IsMandatory: true,
      IsChecked: null,
      AcordCode: "IH053",
      File: "",
      Dmspath: "",
    },
  ],
  PolicyCoverages: {
    Coverages: [
      {
        Carrier: null,
        Name: "BI Coverage",
        Description: "BI Coverage",
        Type: "",
        SettlementType: "",
        Value: "",
        Limit: "25000",
        LimitAmount: "0",
        Deductible: "500",
        IsApplicable: true,
        IsSelected: true,
        IsMandatory: true,
        Status: "",
      },
      {
        Carrier: null,
        Name: "SignatureType",
        Description: "Signature Type",
        Type: "",
        SettlementType: "",
        Value: "",
        Limit: "25000",
        LimitAmount: "0",
        Deductible: "500",
        IsApplicable: true,
        IsSelected: true,
        IsMandatory: true,
        Status: "",
      },
    ],
  },
  PremiumFactors: [
    {
      Name: "RP",
      Status: "Active",
      Type: "",
      Description: "Risk Premium",
      IsApplicable: true,
      IsSelected: true,
      IsMandatory: true,
      Rate: 0,
      Limit: "0",
      LimitAmount: "0",
      Deductible: "0",
      Premium: 0,
      EffectivePremium: 0,
      AnnualPremium: null,
      PremiumDifference: 0,
      Factor: {
        Name: "RP",
        Type: "",
        Description: "Risk Premium",
        Rate: 0,
        Limit: "0",
        LimitAmount: "0",
        Premium: 0,
        Status: "",
        IsApplicable: false,
        IsSelected: false,
        IsMandatory: false,
        Deductible: "0",
        EffectivePremium: 0,
        AnnualPremium: null,
      },
    },
    {
      Name: "MinPre",
      Status: "Active",
      Type: "",
      Description: "Minimum Premium",
      IsApplicable: true,
      IsSelected: true,
      IsMandatory: false,
      Rate: 0,
      Limit: "0",
      LimitAmount: "0",
      Deductible: "0",
      Premium: 0,
      EffectivePremium: 0,
      AnnualPremium: null,
      PremiumDifference: 0,
      Factor: {
        Name: "MinPre",
        Type: "",
        Description: "Minimum Premium",
        Rate: 0,
        Limit: "0",
        LimitAmount: "0",
        Premium: 0,
        Status: "",
        IsApplicable: false,
        IsSelected: false,
        IsMandatory: false,
        Deductible: "0",
        EffectivePremium: 0,
        AnnualPremium: null,
      },
    },
  ],
  TotalPremium: {
    BasicPremium: 2634,
    Surcharge: 0,
    Discount: 0,
    MinPremium: 0,
    EffectivePremium: 699.96,
    AnnualPremium: 2634,
    PriorAnnualPremium: 1732,
    EffectivePremiumWithFeesAndTaxes: 699.96,
    AnnualPremiumWithFeesAndTaxes: 2716,
    OOSPremium: null,
  },
  FeesAndTaxes: [
    {
      Code: "INSFEE",
      Description: "Installment Fee",
      Type: "Fee",
      IsOverride: false,
      Status: "Active",
      Value: 0,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 0,
      IsProRated: null,
    },
    {
      Code: "SR22FEE",
      Description: "SR22 Fee",
      Type: "Fee",
      IsOverride: true,
      Status: "Active",
      Value: 0,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 0,
      IsProRated: null,
    },
    {
      Code: "SR22AFEE",
      Description: "SR22A Fee",
      Type: "Fee",
      IsOverride: true,
      Status: "Active",
      Value: 0,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 0,
      IsProRated: null,
    },
    {
      Code: "PFEE",
      Description: "Policy Fee",
      Type: "Fee",
      IsOverride: false,
      Status: "Active",
      Value: 30,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 30,
      IsProRated: null,
    },
    {
      Code: "NSD",
      Description: "NSD Fee",
      Type: "Fee",
      IsOverride: true,
      Status: "Active",
      Value: 0,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 0,
      IsProRated: null,
    },
    {
      Code: "SERVICEFEE",
      Description: "Service Fee",
      Type: "Fee",
      IsOverride: true,
      Status: "Active",
      Value: 52,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 52,
      IsProRated: null,
    },
    {
      Code: "NSDTRAVELCLUB",
      Description: "ADD Fee",
      Type: "Fee",
      IsOverride: true,
      Status: "Active",
      Value: 0,
      ValueType: "V",
      Amount: 0,
      AnnualAmount: 0,
      IsProRated: null,
    },
  ],
  Risks: {
    Vehicles: [
      {
        UnitId: 1,
        UnitNumber: "1",
        Name: "Vehicle",
        UnitType: "Vehicle",
        Status: "Valid",
        IsDeleted: false,
        IsNewlyAdded: null,
        AdditionalParties: [
          {
            Status: "Active",
            Name: "bank of america",
            ReferenceNumber: "132456",
            IsPayee: true,
            PartyType: "Mortgagee",
            InterestType: "Mortgagee",
            CreatedOn: "2018-08-18",
            DeletedOn: "2022-11-30",
          },
        ],
        VehicleRiskAttributes: {
          ClassificationType: "",
          SecondaryUse: "",
          SecondaryUsePercent: "",
          VehicleType: "",
          VIN: "1HGFA16828L107895",
          Year: "2008",
          VehicleAge: "",
          Make: "HOND",
          Model: "CIVIC EX                               ",
          OwnedOrLeased: "",
          BusinessUseClass: "",
          SizeClass: "",
          GROSSCOMBWEIGHT: "",
          RADIUSCLASSTYPE: "",
          VEHPRICE: "",
          PASSIVERESTR: false,
          VEHYEAR: "",
          ANTILOCKBRAKES: false,
          COSTTYPE: "",
          FARTHESTLOCCITY: "",
          FARTHESTLOCCOUNTY: "",
          FARTHESTLOCSTATE: "",
          FARTHESTLOC: "",
          ISVEHICLEUPLOADED: true,
          COMPDED: "",
          COLLDED: "",
          MPDED: "",
          HASPD: "",
          HASMP: "",
          TEMPLATENAME: "",
          UWREFMSG: "",
          GARAGELOC: "",
          HASRENTAL: "",
          CSLLIMIT: "",
          LIABDED: "",
          UMTYPE: "",
          UMDED: "",
          UMLIMIT: "",
          PrimaryGaragingLocation: [
            {
              Number: 1,
              AddressType: "Primary",
              IsManual: false,
              Description: "Mailing Address",
              AddressLine1: "1345 South Ga Avenue",
              AddressLine2: "",
              AptSuite: "",
              City: "Bremen",
              County: "Haralson County",
              CountyCode: "",
              State: "GA",
              PoBox: "",
              Postalcode: "30110",
              FormattedAddress: "1345 Old Carrollton Road",
              UnFormattedAddress: "1345 South Ga Avenue, Bremen, GA, USA",
              AdministrationArea1: "",
              AdministrationArea2: "",
              Locality: "",
              Lat: "",
              Long: "",
              Name: "",
              Premise: "",
              Status: "",
              Territory: "",
              Business: "",
              PlaceId:
                "EiUxMzQ1IFNvdXRoIEdhIEF2ZW51ZSwgQnJlbWVuLCBHQSwgVVNBIjESLwoUChIJxV-khQXYiogRvepDM0izozYQwQoqFAoSCSVwAd4O2IqIEceomtvTuXsV",
              AptSuiteLot: "Apt",
              Street: "1345 Old Carrollton Road",
              StreetName: "1345 Old Carrollton Road",
            },
          ],
          AdditionalInterestDetails: [],
          HasAdditionalInterestDetails: false,
          SymbolOTC: "15",
          SymbolColl: "15",
          SymbolLiab: "34",
          SymbolMP: "5524",
          OTCDeductible: "500",
          CollDeductible: "500",
          IsGaragingSameAsMailing: true,
          IncludePunitiveDamages: "Y",
          IsDNI: false,
          AnnualMileage: "<5000",
          BodyStyle: "SEDAN 4D",
          MechanicalDesc: " N000000  ",
          IsNonOwnerPolicy: false,
          VerifiedVIN: true,
          Towing: "",
          Rental: "",
          Use: "PL",
          AirbagDisc: false,
          AssignedDriver: "2",
          SoftDelete: "false",
          VehicleLoadCapacity: 0,
          IsBusinessUse: "false",
        },
        Coverages: [
          {
            Carrier: "",
            Name: "BI Coverage",
            Description: "Bodily Injury Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "500",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "PD Coverage",
            Description: "Property Damage Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "500",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "UMBI Coverage",
            Description: "Uninsured Motorist Bodily Injury Coverage",
            Type: "",
            SettlementType: "R",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "UMPD Coverage",
            Description: "Uninsured Motorist Property Damage Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "0",
            Deductible: "250",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Medical Payment Coverage",
            Description: "Medical Payment Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "NoCov",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Towing And Labor Coverage",
            Description: "Towing And Labor Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Rental Reimbursement Coverage",
            Description: "Rental Reimbursement Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "COMP",
            Description: "Other than Collision Deductible",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "COLL",
            Description: "Collision Deductible",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
        ],
        PremiumFactors: [
          {
            Name: "BI",
            Status: "Active",
            Type: "",
            Description: "BI Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 230,
            EffectivePremium: -145.112,
            AnnualPremium: null,
            PremiumDifference: -187,
            Factor: {
              Name: "BI",
              Type: "",
              Description: "BI Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 230,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "PD",
            Status: "Active",
            Type: "",
            Description: "PD Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 229,
            EffectivePremium: -145.888,
            AnnualPremium: null,
            PremiumDifference: -188,
            Factor: {
              Name: "PD",
              Type: "",
              Description: "PD Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 229,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "MP",
            Status: "Active",
            Type: "",
            Description: "Medical Payment Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "MP",
              Type: "",
              Description: "Medical Payment Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "CMP",
            Status: "Active",
            Type: "",
            Description: "COMP",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 115,
            EffectivePremium: -37.248000000000005,
            AnnualPremium: null,
            PremiumDifference: -48,
            Factor: {
              Name: "CMP",
              Type: "",
              Description: "COMP",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 115,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "COL",
            Status: "Active",
            Type: "",
            Description: "COLL",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 466,
            EffectivePremium: -148.216,
            AnnualPremium: null,
            PremiumDifference: -191,
            Factor: {
              Name: "COL",
              Type: "",
              Description: "COLL",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 466,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "TOW",
            Status: "Active",
            Type: "",
            Description: "Towing And Labor Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "TOW",
              Type: "",
              Description: "Towing And Labor Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "RNT",
            Status: "Active",
            Type: "",
            Description: "Rental Reimbursement Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "RNT",
              Type: "",
              Description: "Rental Reimbursement Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "FFH",
            Status: "Active",
            Type: "",
            Description: "FFH LIMITS (SG Only)",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "FFH",
              Type: "",
              Description: "FFH LIMITS (SG Only)",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "URB",
            Status: "Active",
            Type: "",
            Description: "UMBI Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 39,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "URB",
              Type: "",
              Description: "UMBI Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 39,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "URP",
            Status: "Active",
            Type: "",
            Description: "UMPD Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 39,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "URP",
              Type: "",
              Description: "UMPD Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 39,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
        ],
        Premium: {
          BasicPremium: null,
          Surcharge: 0,
          Discount: 0,
          MinPremium: null,
          EffectivePremium: -476.46,
          AnnualPremium: 1118,
          EffectivePremiumWithFeesAndTaxes: null,
          AnnualPremiumWithFeesAndTaxes: null,
        },
        Audit: {
          CreatedBy: "",
          CreatedOn: "",
          DeletedOn: "",
          LastUpdatedBy: "",
          LastUpdatedOn: "",
        },
      },
      {
        UnitId: 1,
        UnitNumber: "2",
        Name: "Vehicle",
        UnitType: "Vehicle",
        Status: "Valid",
        IsDeleted: false,
        IsNewlyAdded: true,
        AdditionalParties: [
          {
            Status: "Active",
            Name: "bank of america",
            ReferenceNumber: "132456",
            IsPayee: true,
            PartyType: "Mortgagee",
            InterestType: "Mortgagee",
            CreatedOn: "2018-08-18",
            DeletedOn: "2022-11-30",
          },
        ],
        VehicleRiskAttributes: {
          ClassificationType: "",
          SecondaryUse: "",
          SecondaryUsePercent: "",
          VehicleType: "",
          VIN: "1FADP3K2XEL147046",
          Year: "2014",
          VehicleAge: "",
          Make: "FORD",
          Model: "FOCUS SE                               ",
          OwnedOrLeased: "",
          BusinessUseClass: "",
          SizeClass: "",
          GROSSCOMBWEIGHT: "",
          RADIUSCLASSTYPE: "",
          VEHPRICE: "",
          PASSIVERESTR: false,
          VEHYEAR: "",
          ANTILOCKBRAKES: false,
          COSTTYPE: "",
          FARTHESTLOCCITY: "",
          FARTHESTLOCCOUNTY: "",
          FARTHESTLOCSTATE: "",
          FARTHESTLOC: "",
          ISVEHICLEUPLOADED: true,
          COMPDED: "",
          COLLDED: "",
          MPDED: "",
          HASPD: "",
          HASMP: "",
          TEMPLATENAME: "",
          UWREFMSG: "",
          GARAGELOC: "",
          HASRENTAL: "",
          CSLLIMIT: "",
          LIABDED: "",
          UMTYPE: "",
          UMDED: "",
          UMLIMIT: "",
          PrimaryGaragingLocation: [
            {
              Number: 1,
              AddressType: "Primary",
              IsManual: false,
              Description: "Mailing Address",
              AddressLine1: "1345 South Ga Avenue",
              AddressLine2: "",
              AptSuite: "",
              City: "Bremen",
              County: "Haralson County",
              CountyCode: "",
              State: "GA",
              PoBox: "",
              Postalcode: "30110",
              FormattedAddress: "1345 Old Carrollton Road",
              UnFormattedAddress: "1345 South Ga Avenue, Bremen, GA, USA",
              AdministrationArea1: "",
              AdministrationArea2: "",
              Locality: "",
              Lat: "",
              Long: "",
              Name: "",
              Premise: "",
              Status: "",
              Territory: "",
              Business: "",
              PlaceId:
                "EiUxMzQ1IFNvdXRoIEdhIEF2ZW51ZSwgQnJlbWVuLCBHQSwgVVNBIjESLwoUChIJxV-khQXYiogRvepDM0izozYQwQoqFAoSCSVwAd4O2IqIEceomtvTuXsV",
              AptSuiteLot: "Apt",
              Street: "1345 Old Carrollton Road",
              StreetName: "1345 Old Carrollton Road",
            },
          ],
          AdditionalInterestDetails: [],
          HasAdditionalInterestDetails: false,
          SymbolOTC: "23",
          SymbolColl: "34",
          SymbolLiab: "34",
          SymbolMP: "3471",
          OTCDeductible: "500",
          CollDeductible: "500",
          IsGaragingSameAsMailing: true,
          IncludePunitiveDamages: "N",
          IsDNI: false,
          AnnualMileage: "<5000",
          BodyStyle: "HCHBK 4D",
          MechanicalDesc: " S000000  ",
          IsNonOwnerPolicy: false,
          VerifiedVIN: true,
          Towing: "",
          Rental: "",
          Use: "PL",
          AirbagDisc: false,
          AssignedDriver: "1",
          SoftDelete: "false",
          VehicleLoadCapacity: 0,
          IsBusinessUse: "false",
        },
        Coverages: [
          {
            Carrier: "",
            Name: "BI Coverage",
            Description: "Bodily Injury Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "500",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "PD Coverage",
            Description: "Property Damage Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "500",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "UMBI Coverage",
            Description: "Uninsured Motorist Bodily Injury Coverage",
            Type: "",
            SettlementType: "R",
            Value: "",
            Limit: "25000",
            LimitAmount: "50000",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "UMPD Coverage",
            Description: "Uninsured Motorist Property Damage Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "25000",
            LimitAmount: "0",
            Deductible: "250",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Medical Payment Coverage",
            Description: "Medical Payment Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "NoCov",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Towing And Labor Coverage",
            Description: "Towing And Labor Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "Rental Reimbursement Coverage",
            Description: "Rental Reimbursement Coverage",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "COMP",
            Description: "Other than Collision Deductible",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
          {
            Carrier: "",
            Name: "COLL",
            Description: "Collision Deductible",
            Type: "",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
        ],
        PremiumFactors: [
          {
            Name: "PDCollNZ",
            Status: "Active",
            Type: "SUR",
            Description: "Physical Damage Rating - Collision(Non-Zone)",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Rate: 0,
            Limit: "100",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "PDCollNZ",
              Type: "SUR",
              Description: "Physical Damage Rating - Collision(Non-Zone)",
              Rate: 0,
              Limit: "100",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: true,
              IsSelected: true,
              IsMandatory: true,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "BI",
            Status: "Active",
            Type: "",
            Description: "BI Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 282,
            EffectivePremium: 218.832,
            AnnualPremium: null,
            PremiumDifference: 282,
            Factor: {
              Name: "BI",
              Type: "",
              Description: "BI Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 282,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "PD",
            Status: "Active",
            Type: "",
            Description: "PD Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 282,
            EffectivePremium: 218.832,
            AnnualPremium: null,
            PremiumDifference: 282,
            Factor: {
              Name: "PD",
              Type: "",
              Description: "PD Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 282,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "MP",
            Status: "Active",
            Type: "",
            Description: "Medical Payment Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "MP",
              Type: "",
              Description: "Medical Payment Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "CMP",
            Status: "Active",
            Type: "",
            Description: "COMP",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 146,
            EffectivePremium: 113.296,
            AnnualPremium: null,
            PremiumDifference: 146,
            Factor: {
              Name: "CMP",
              Type: "",
              Description: "COMP",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 146,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "COL",
            Status: "Active",
            Type: "",
            Description: "COLL",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 728,
            EffectivePremium: 564.928,
            AnnualPremium: null,
            PremiumDifference: 728,
            Factor: {
              Name: "COL",
              Type: "",
              Description: "COLL",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 728,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "TOW",
            Status: "Active",
            Type: "",
            Description: "Towing And Labor Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "TOW",
              Type: "",
              Description: "Towing And Labor Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "RNT",
            Status: "Active",
            Type: "",
            Description: "Rental Reimbursement Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "RNT",
              Type: "",
              Description: "Rental Reimbursement Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "FFH",
            Status: "Active",
            Type: "",
            Description: "FFH LIMITS (SG Only)",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "FFH",
              Type: "",
              Description: "FFH LIMITS (SG Only)",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 0,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "URB",
            Status: "Active",
            Type: "",
            Description: "UMBI Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 39,
            EffectivePremium: 30.264,
            AnnualPremium: null,
            PremiumDifference: 39,
            Factor: {
              Name: "URB",
              Type: "",
              Description: "UMBI Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 39,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
          {
            Name: "URP",
            Status: "Active",
            Type: "",
            Description: "UMPD Coverage",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: false,
            Rate: 0,
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 39,
            EffectivePremium: 30.264,
            AnnualPremium: null,
            PremiumDifference: 39,
            Factor: {
              Name: "URP",
              Type: "",
              Description: "UMPD Coverage",
              Rate: 0,
              Limit: "0",
              LimitAmount: "0",
              Premium: 39,
              Status: "",
              IsApplicable: false,
              IsSelected: false,
              IsMandatory: false,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
        ],
        Premium: {
          BasicPremium: null,
          Surcharge: 0,
          Discount: 0,
          MinPremium: null,
          EffectivePremium: 1176.42,
          AnnualPremium: 1516,
          EffectivePremiumWithFeesAndTaxes: null,
          AnnualPremiumWithFeesAndTaxes: null,
        },
        Audit: {
          CreatedBy: "",
          CreatedOn: "",
          DeletedOn: "",
          LastUpdatedBy: "",
          LastUpdatedOn: "",
        },
      },
    ],
    Drivers: [
      {
        UnitId: 1,
        UnitNumber: "1",
        Name: "Driver",
        UnitType: "Driver",
        Status: "Valid",
        IsDeleted: false,
        IsNewlyAdded: null,
        DriverRiskAttributes: {
          Type: "Principal",
          PrevType: "Principal",
          FirstName: "ALICE",
          MiddleName: "",
          LastName: "BURNS",
          Suffix: "",
          DOB: "1996-03-04",
          Age: 27,
          Experience: 11,
          LicenseNumber: "987654321",
          Violations: 0,
          IsUSCitizen: true,
          Occupation: "UN",
          OtherOccupation: "test",
          FilingStatusCode: "",
          Fillings: {
            Fillings: "No",
            Date: "",
            Reason: "",
            FilingCd: "",
            FilingStatusCd: "",
          },
          FilingCode: "",
          LicenseDate: "",
          State: "GA",
          HadTrainingCourse: false,
          IsMilitary: false,
          MilitaryRank: "",
          HadDUIDWI: false,
          DriverCourseCompletedDate: "",
          CanInsureOperate: false,
          LicenseStatus: "Valid",
          IsGoodStudentDiscountApplicable: false,
          MaritalStatus: "S",
          Gender: "M",
          Violation: [],
          RelationToApplicant: "Insured",
          IsDNI: false,
          IsEditing: true,
          SSN: "",
          AgeWhenFirstLicensed: "16",
          MVRCount: 0,
          MVRViolationStatus: "No Hit",
          IsVerifiedBy: "ClueMvr",
        },
        Coverages: [
          {
            Carrier: null,
            Name: "Combined Single Limit",
            Description: "Combined Single Limit",
            Type: "Coverage",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
        ],
        PremiumFactors: [
          {
            Name: "PDCollNZ",
            Status: "Active",
            Type: "SUR",
            Description: "Physical Damage Rating - Collision(Non-Zone)",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Rate: 0,
            Limit: "100",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "PDCollNZ",
              Type: "SUR",
              Description: "Physical Damage Rating - Collision(Non-Zone)",
              Rate: 0,
              Limit: "100",
              LimitAmount: "0",
              Premium: 0,
              Status: null,
              IsApplicable: true,
              IsSelected: true,
              IsMandatory: true,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
        ],
        Premium: {
          BasicPremium: null,
          Surcharge: 0,
          Discount: 0,
          MinPremium: null,
          EffectivePremium: 0,
          AnnualPremium: 0,
          EffectivePremiumWithFeesAndTaxes: null,
          AnnualPremiumWithFeesAndTaxes: null,
        },
        Audit: {
          CreatedBy: "",
          CreatedOn: "",
          DeletedOn: "",
          LastUpdatedBy: "",
          LastUpdatedOn: "",
        },
      },
      {
        UnitId: 1,
        UnitNumber: "2",
        Name: "Driver",
        UnitType: "Driver",
        Status: "Valid",
        IsDeleted: false,
        IsNewlyAdded: true,
        DriverRiskAttributes: {
          Type: "Principal",
          PrevType: "Principal",
          FirstName: "Ananya",
          MiddleName: "",
          LastName: "Singh",
          Suffix: "",
          DOB: "2000-11-16",
          Age: 22,
          Experience: 6,
          LicenseNumber: "987987569",
          Violations: 0,
          IsUSCitizen: true,
          Occupation: "TES",
          OtherOccupation: "",
          FilingStatusCode: "",
          Fillings: {
            Fillings: "No",
            Date: "",
            Reason: "",
            FilingCd: "",
            FilingStatusCd: "",
          },
          FilingCode: "",
          LicenseDate: "",
          State: "GA",
          HadTrainingCourse: false,
          IsMilitary: false,
          MilitaryRank: "",
          HadDUIDWI: false,
          DriverCourseCompletedDate: "",
          CanInsureOperate: false,
          LicenseStatus: "Valid",
          IsGoodStudentDiscountApplicable: false,
          MaritalStatus: "S",
          Gender: "F",
          Violation: [],
          RelationToApplicant: "Other",
          IsDNI: false,
          IsEditing: false,
          SSN: "",
          AgeWhenFirstLicensed: "16",
          MVRCount: 0,
          MVRViolationStatus: "",
          IsVerifiedBy: "",
        },
        Coverages: [
          {
            Carrier: null,
            Name: "Combined Single Limit",
            Description: "Combined Single Limit",
            Type: "Coverage",
            SettlementType: "",
            Value: "",
            Limit: "0",
            LimitAmount: "0",
            Deductible: "0",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Status: "",
          },
        ],
        PremiumFactors: [
          {
            Name: "PDCollNZ",
            Status: "Active",
            Type: "SUR",
            Description: "Physical Damage Rating - Collision(Non-Zone)",
            IsApplicable: true,
            IsSelected: true,
            IsMandatory: true,
            Rate: 0,
            Limit: "100",
            LimitAmount: "0",
            Deductible: "0",
            Premium: 0,
            EffectivePremium: 0,
            AnnualPremium: null,
            PremiumDifference: 0,
            Factor: {
              Name: "PDCollNZ",
              Type: "SUR",
              Description: "Physical Damage Rating - Collision(Non-Zone)",
              Rate: 0,
              Limit: "100",
              LimitAmount: "0",
              Premium: 0,
              Status: null,
              IsApplicable: true,
              IsSelected: true,
              IsMandatory: true,
              Deductible: "0",
              EffectivePremium: 0,
              AnnualPremium: null,
            },
          },
        ],
        Premium: {
          BasicPremium: null,
          Surcharge: 0,
          Discount: 0,
          MinPremium: null,
          EffectivePremium: 0,
          AnnualPremium: 0,
          EffectivePremiumWithFeesAndTaxes: null,
          AnnualPremiumWithFeesAndTaxes: null,
        },
        Audit: {
          CreatedBy: "",
          CreatedOn: "",
          DeletedOn: "",
          LastUpdatedBy: "",
          LastUpdatedOn: "",
        },
      },
    ],
  },
  Rules: {
    Action: "Allow",
    MatchingRules: [],
  },
  PreviousPolicies: {
    IsPreviousPolicy: true,
    PreviousPolicyNumber: "",
    OtherCoverages: "",
    IsPreviousClaims: true,
    NoOfClaims: 0,
    TotalAmountClaimed: 0,
  },
  Underwriting: [
    {
      Code: "physicalImpairment",
      Key: "Do any of the vehicle operators have physical impairments that would impact their ability to drive?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "infrequentBasis",
      Key: "Have all drivers, such as children away from home or in college who may operate a vehicle on a regular basis or any infrequent basis been listed on this application?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "ageDisclosed",
      Key: "Have all residents in the household age 15 or older been disclosed on this application?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "notStationed",
      Key: "Is any driver a member of the armed forces not stationed in Georgia/North Carolina?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "agreeToNotify",
      Key: "The applicant agrees to notify Southern General of any member of the household age 15 and older, licensed or not, and any change in driving status for any person currently listed or added on the policy in the future.",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "undisclosedDriver",
      Key: "The applicant understands that Southern General may not cover a loss to a vehicle which is being operated by an undisclosed driver that lives in the household.",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "unrepairedDamage",
      Key: "Is there any unrepaired damage to the vehicles?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "allVehiclesListed",
      Key: "Have all vehicles in the household been listed on this application?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "allVehicleTitled",
      Key: "Are all vehicles on the policy titled or tagged in the named insured's name or spouse?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "whichNameTagged",
      Key: "Please Select which name is used on the title/tag?",
      Value: "",
      Remark: "",
      Optional: [],
    },
    {
      Code: "requiredInspection",
      Key: "Have all vehicles requiring physical damage coverage been inspected by the agent?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "garagedInState",
      Key: "Are all vehicles in the household garaged in the state at least ten months out of the year?",
      Value: "true",
      Remark: "",
      Optional: [],
    },
    {
      Code: "provideService",
      Key: "Are any vehicles used to provide services for “Transport Network Companies” including but not limited to Uber, Lyft etc.?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "usedInDNP",
      Key: "Are any vehicles used in a “Delivery Network Platform” such as DoorDash, Instacart, Grubhub, etc.?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "convictedOfFelony",
      Key: "Have any driver(s) ever been convicted of a felony?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
    {
      Code: "businessUse",
      Key: "Does your trade, occupation, profession, or business require the use of any listed motor vehicle?",
      Value: "false",
      Remark: "",
      Optional: [],
    },
  ],
  NonFunctional: {
    LastSubmittedPage: "/Personal/Auto/Cancel/Landing-Billing",
    Milestones: [0, 1, 2, 3, 4, 5],
  },
  Payplan: [
    {
      DownPaymentPercentage: 18,
      DownPaymentCode: "HHR1",
      DownPaymentDueDays: "2023-04-26",
      DownPaymentAmount: 488.88,
      PayInFull: "",
      NoOfInstallments: 4,
      MoreThanDPAmount: "",
      IsSelected: "",
      PPDescription: "4-Pay 18.00% Dn",
      Installments: [
        {
          InstallmentNumber: 0,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-07-08T11:15:58.426Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 1,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-09-06T11:15:58.426Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 2,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-12-05T11:15:58.426Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 3,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2024-04-03T11:15:58.426Z",
          IsSelected: null,
        },
      ],
    },
    {
      DownPaymentPercentage: 20,
      DownPaymentCode: "GGX6",
      DownPaymentDueDays: "2023-04-26",
      DownPaymentAmount: 543.2,
      PayInFull: "",
      NoOfInstallments: 5,
      MoreThanDPAmount: "",
      IsSelected: "",
      PPDescription: "5-Pay 20.00% Dn",
      Installments: [
        {
          InstallmentNumber: 0,
          BillingPlan: "Sample Plan",
          DownPay: 447.56000000000006,
          Payments: 0,
          Date: "2023-05-26",
          IsSelected: "",
        },
        {
          InstallmentNumber: 1,
          BillingPlan: "Sample Plan",
          DownPay: 447.56000000000006,
          Payments: 0,
          Date: "2023-06-25",
          IsSelected: "",
        },
        {
          InstallmentNumber: 2,
          BillingPlan: "Sample Plan",
          DownPay: 447.56000000000006,
          Payments: 0,
          Date: "2023-07-25",
          IsSelected: "",
        },
        {
          InstallmentNumber: 3,
          BillingPlan: "Sample Plan",
          DownPay: 447.56000000000006,
          Payments: 0,
          Date: "2023-08-24",
          IsSelected: "",
        },
        {
          InstallmentNumber: 4,
          BillingPlan: "Sample Plan",
          DownPay: 447.56000000000006,
          Payments: 0,
          Date: "2023-09-23",
          IsSelected: "",
        },
      ],
    },
    {
      DownPaymentPercentage: 24,
      DownPaymentCode: "DCF3",
      DownPaymentDueDays: "2023-04-26",
      DownPaymentAmount: 651.84,
      PayInFull: "",
      NoOfInstallments: 5,
      MoreThanDPAmount: "",
      IsSelected: "",
      PPDescription: "5-Pay 24.00% Dn",
      Installments: [
        {
          InstallmentNumber: 0,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-07-08T11:12:00.378Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 1,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-09-06T11:12:00.378Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 2,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2023-12-05T11:12:00.378Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 3,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2024-04-03T11:12:00.378Z",
          IsSelected: null,
        },
        {
          InstallmentNumber: 4,
          BillingPlan: "DC",
          DownPay: null,
          Payments: null,
          Date: "2024-08-31T11:12:00.378Z",
          IsSelected: null,
        },
      ],
    },
    {
      DownPaymentPercentage: 31,
      DownPaymentCode: "GGK1",
      DownPaymentDueDays: "2023-04-26",
      DownPaymentAmount: 841.96,
      PayInFull: "",
      NoOfInstallments: 5,
      MoreThanDPAmount: "",
      IsSelected: "",
      PPDescription: "5-Pay 31.00% Dn",
      Installments: [
        {
          InstallmentNumber: 0,
          BillingPlan: "Sample Plan",
          DownPay: 387.808,
          Payments: 0,
          Date: "2023-05-26",
          IsSelected: "",
        },
        {
          InstallmentNumber: 1,
          BillingPlan: "Sample Plan",
          DownPay: 387.808,
          Payments: 0,
          Date: "2023-06-25",
          IsSelected: "",
        },
        {
          InstallmentNumber: 2,
          BillingPlan: "Sample Plan",
          DownPay: 387.808,
          Payments: 0,
          Date: "2023-07-25",
          IsSelected: "",
        },
        {
          InstallmentNumber: 3,
          BillingPlan: "Sample Plan",
          DownPay: 387.808,
          Payments: 0,
          Date: "2023-08-24",
          IsSelected: "",
        },
        {
          InstallmentNumber: 4,
          BillingPlan: "Sample Plan",
          DownPay: 387.808,
          Payments: 0,
          Date: "2023-09-23",
          IsSelected: "",
        },
      ],
    },
    {
      DownPaymentPercentage: 100,
      DownPaymentCode: "EFD1",
      DownPaymentDueDays: "2023-04-26",
      DownPaymentAmount: 2716,
      PayInFull: "",
      NoOfInstallments: null,
      MoreThanDPAmount: "",
      IsSelected: "",
      PPDescription: "1 PAY",
      Installments: [],
    },
  ],
  Payments: [
    {
      LastName: "",
      FirstName: "",
      OrderID: "",
      TransactionType: "Direct Bill",
      TransactionID: "",
      TransactionDate: "2023-04-26",
      TransactionStatus: "",
      TransactionAmount: 568.703,
      CardDetails: {
        Type: "",
        CardNumber: "",
        Expiry: "",
        CVVCode: "",
        LastFourDigits: "",
      },
      BankDetails: {
        AccountName: "",
        BankName: "",
        BranchName: "",
        AccountType: "",
        RoutingNo: "",
      },
    },
  ],
  DiscountAndSurcharges: [
    {
      Name: "SafeDriver",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "FaultAccidentFree",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "PaidInFull",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "ResidenceType",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "N",
    },
    {
      Name: "ProofOfPrior",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "false",
    },
    {
      Name: "SixMonthsPriorCoverage",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "NewBusiness",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "NSDMotorClub",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "ADDTravelClub",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "ADDLimit",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "PriorPolicyListedAs",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "DurationInsuredWithPresentAgency",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "PremiumOptionSelected",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "DaysLapsed",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "NamedDriverAutoLimitation",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "GoodStudentDiscount",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "PaperlessDiscount",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "DefensiveDriver",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "MultiCar",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "EarlyQBind",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "ThreeYearAtFault",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "FullCoverage",
      Type: "",
      Amount: 0,
      IsApplied: true,
      Value: "",
    },
    {
      Name: "AirbagDiscount",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "AgencyTransfer",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "PhysicalConditionStatement",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "HasRentalInsurance",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "FirstName",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "MiddleName",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "LastName",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
    {
      Name: "Relationship",
      Type: "",
      Amount: 0,
      IsApplied: false,
      Value: "",
    },
  ],
  ReconciliationFlags: {
    LiabilityPolicy: "false",
    ClueCount: 1,
    ClueVioationStatus: "No Hit",
  },
  OOS: null,
  UnderwritingTier: null,
  FinancialTier: null,
  ForceRetiering: null,
  ActivityCode: null,
  UMAddedReducedIndex: null,
  PreferredAgency: null,
  SelectStackUM: null,
  UnderwritingNew: null,
};

const uiSchema = [
  {
		"key": "PolicyDetails",
		"type": "Card",
		"title": "Policy Details",
		"className": " clearfix",
		"titleClassName": "commonHead commonHeadPadding",
		"childsClassName": "boxWrapper px-3 commonShadow",
		"controls": [
			{
				"key": "businessname",
				"label": "Prem Corp",
				"type": "label",
				"value": "Business Name",
				"props": {},
				"labelClass": "inputLabel ddlUnderwriterList",
				"positionClass": "col-md-4",
				"isColummnDisplay": false
			},
			{
				"key": "mailingaddress",
				"label": "322 Texas 3, League City, TX, USA, 77573",
				"type": "label",
				"value": "Mailing Address",
				"props": {},
				"labelClass": "inputLabel ddlUnderwriterList",
				"positionClass": "col-md-4",
				"isColummnDisplay": false
			},
			{
				"key": "lineOfBusiness",
				"label": "Auto Physical Damage (APD)",
				"type": "label",
				"value": "Line of Business",
				"props": {},
				"labelClass": "inputLabel ddlUnderwriterList",
				"positionClass": "col-md-4",
				"isColummnDisplay": false
			},
			{
				"key": "policyeffectivedate",
				"label": "06/30/2023",
				"value": "Policy start date",
				"type": "label",
				"props": {},
				"labelClass": "inputLabel ddlUnderwriterList",
				"positionClass": "col-md-4 mt-4",
				"isColummnDisplay": false
			},
			{
				"key": "policyenddate",
				"label": "06/30/2024",
				"type": "label",
				"value": "Policy end date",
				"props": {},
				"labelClass": "ddlUnderwriterList",
				"positionClass": "col-md-4 mt-4",
				"isColummnDisplay": false
			},
			{
				"key": "policynumber",
				"label": "CUS050APD000111-00",
				"type": "label",
				"value": "Policy Number",
				"props": {
					"required": true,
					"disabled": true
				},
				"labelClass": "inputLabel ddlUnderwriterList",
				"positionClass": "col-md-4 mt-4",
				"isColummnDisplay": false
			}
		]
	},
  {
    key: "ReinstatementDetails",
    type: "Card",
    title: "Reinstatement Details",
    className: " mt-4",
    titleClassName: "commonHead commonHeadPadding",
    childsClassName: "boxWrapper px-3 commonShadow",
    controls: [
      {
        key: "reinstatementeffectivedate",
        label: "Reinstatement Effective Date*",
        type: "date",
        props: {
          required: true,
          class: "inputText",
          disabled: true,
        },
        positionClass: "col-md-4",
        isColummnDisplay: false,
        errorMessage: "Please select Valid Date",
        dataPath: "Transaction.EffectiveDate",
      },
      {
        key: "reason",
        label: "Reinstatement Reason*",
        type: "select",
        props: {
          required: true,
          class: "inputText",
          disabled: true,
        },
        labelClass: "inputLabel",
        positionClass: "col-md-4",
        isColummnDisplay: false,
        options: [
          {
            key: "Please Select",
            label: "Please Select",
            value: "",
          },
          {
            positionClass: "col-md-4",
            name: "Insured Request",
            key: "Insured Request",
            label: "Insured Request",
            value: "Insured Request",
          },
          {
            positionClass: "col-md-4",
            name: "Non Pay Finance",
            key: "Non Pay Finance",
            label: "Non Pay Finance",
            value: "Non Pay Finance",
          },
          {
            positionClass: "col-md-4",
            name: "Double Coverage",
            key: "Double Coverage",
            label: "Double Coverage",
            value: "Double Coverage",
          },
          {
            positionClass: "col-md-4",
            name: "VOID AB INITIO",
            key: "VOID AB INITIO",
            label: "VOID AB INITIO",
            value: "VOID AB INITIO",
          },
          {
            positionClass: "col-md-4",
            name: "MMR-During Review Period",
            key: "MMR-During Review Period",
            label: "MMR-During Review Period",
            value: "MMR-During Review Period",
          },
          {
            positionClass: "col-md-4",
            name: "MMR-After Review Period",
            key: "MMR-After Review Period",
            label: "MMR-After Review Period",
            value: "MMR-After Review Period",
          },
          {
            positionClass: "col-md-4",
            name: "Out of State",
            key: "Out of State",
            label: "Out of State",
            value: "Out of State",
          },
          {
            positionClass: "col-md-4",
            name: "Recancel back to Orig cancel effective date- PR",
            key: "Recancel back to Orig cancel effective date- PR",
            label: "Recancel back to Orig cancel effective date- PR",
            value: "Recancel back to Orig cancel effective date- PR",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Fail to provide license Info",
            key: "Underwriter's Judgment-Fail to provide license Info",
            label: "Underwriter's Judgment-Fail to provide license Info",
            value: "Underwriter's Judgment-Fail to provide license Info",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-No Excluded driver Endorsement",
            key: "Underwriter's Judgment-No Excluded driver Endorsement",
            label: "Underwriter's Judgment-No Excluded driver Endorsement",
            value: "Underwriter's Judgment-No Excluded driver Endorsement",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Failure to respond to UW memo",
            key: "Underwriter's Judgment-Failure to respond to UW memo",
            label: "Underwriter's Judgment-Failure to respond to UW memo",
            value: "Underwriter's Judgment-Failure to respond to UW memo",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Exceed Mac Violation points",
            key: "Underwriter's Judgment-Exceed Mac Violation points",
            label: "Underwriter's Judgment-Exceed Mac Violation points",
            value: "Underwriter's Judgment-Exceed Mac Violation points",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Ins risk on new drv/veh after rev period",
            key: "Underwriter's Judgment-Ins risk on new drv/veh after rev period",
            label:
              "Underwriter's Judgment-Ins risk on new drv/veh after rev period",
            value:
              "Underwriter's Judgment-Ins risk on new drv/veh after rev period",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Allowing excl driver access to insured veh",
            key: "Underwriter's Judgment-Allowing excl driver access to insured veh",
            label:
              "Underwriter's Judgment-Allowing excl driver access to insured veh",
            value:
              "Underwriter's Judgment-Allowing excl driver access to insured veh",
          },
          {
            positionClass: "col-md-4",
            name: "Underwriter's Judgment-Signed App not rec'd",
            key: "Underwriter's Judgment-Signed App not rec'd",
            label: "Underwriter's Judgment-Signed App not rec'd",
            value: "Underwriter's Judgment-Signed App not rec'd",
          },
          {
            positionClass: "col-md-4",
            name: "Signed Application not Received",
            key: "Signed Application not Received",
            label: "Signed Application not Received",
            value: "Signed Application not Received",
          },
        ],
        errorMessage: "Please select reason",
        dataPath: "Transaction.Reason",
      },
      {
        key: "signatureType",
        label: "Signature Type",
        type: "select",
        props: {
          class: "inputText",
          required: false,
          disabled: false,
        },
        className: "display-none",
        labelClass: "inputLabel",
        positionClass: "col-md-4 mb-3",
        isColummnDisplay: false,
        dataPath: "SignatureType",
        options: [
          {
            key: "SelectSignatureType",
            label: "Please Select",
            value: "",
          },
          {
            key: "electronic",
            label: "Electronic",
            value: "Electronic",
          },
          {
            key: "handwritten",
            label: "Wet/Handwritten",
            value: "Wet/Handwritten",
          },
        ],
      },
      {
        key: "reinstatementterms",
        label: "Reinstatement Terms/Notes",
        type: "textarea",
        value: "",
        props: {
          class: "inputText",
          placeholder: "Enter Reinstatement Notes",
          maxlength: "200",
          disabled: false,
          required: false,
        },
        labelClass: "inputLabel ddlUnderwriterList",
        positionClass: "col-md-4",
        isColummnDisplay: false,
        errorMessage: "Please enter Reinstatement Notes",
        dataPath: "Transaction.Remarks",
      },
    ],
  },
];

const mutationQuery = {
  rateEndorsement: RATE_ENDORSEMENT,
  updatePolicy: UPDATE_POLICY,
  triggerNotification: TRIGGER_NOTIFICATION,
  revertTransaction: REVERT_TRANSACTION,
  bindReinstate: BIND_REINSTATE,
};

const actionName = {
  startReinstatement: "startReinstate",
  RateEndorsement: "rateEndorsement",
  RateEndorse: "rateendorse",
  Revert: "revert",
  BindReinstate: "bindReinstate",
};

const requestedPage = {
  CancelLanding: "/Personal/Auto/Cancel/Landing/",
  ReinstateLanding: "/Personal/Auto/Reinstate/Landing/",
  documentOfNoLoss: "ih/personal/auto/ga/document_of_no_loss.html",
  applicationSummary: "/Personal/Auto/Application/Summary/",
};

const ReinstatementArgs = {
  uiDataModel,
  uiSchema,
  mutationQuery,
  actionName,
  requestedPage,
  keys: {
    reinstateStatus: "Active Policy",
    reinstateHold: 'Reinstatement Request On Hold',
    reinstateReject: 'Policy Cancelled',
    reinstatementRequestOnHold: "Reinstatement Request On Hold"
  },
  save: () => {}, 
  updatePolicyStatus: () => {},
  triggerNotification: () => {}
};

export default {
  title: "Design System/Functional/Reinstatement",
  component: ReinstatementFunctional,
};

const Template = (args) => <ReinstatementFunctional {...args} />;
// export const ReinstatementFunComp = Template.bind({});
// ReinstatementFunComp.args = ReinstatementArgs;
