import gql from 'graphql-tag';
import {
  CORE_POLICY_FIELDS,
  NON_FUNCTIONAL_FIELDS,
  UNDERWRITTING_FIELDS,
  TRANSACTION_FIELDS,
  PREMIUM_FACTORS_FIELDS,
  PREMIUM_FIELDS,
  TOTAL_PREMIUM_FIELDS,
  POLICY_COVERAGES_FIELDS,
  ATTRIBUTES_FIELDS,
  AUDIT_FIELDS,
  DISCOUNT_SURCHARGE_FIELDS,
  RULES_FIELDS,
  FORMS_FIELDS,
  FEES_TAXES_FIELDS,
  EXTERNALREFERENCES_FIELDS,
  INSURED_ACCOUNT_FIELDS,
  RISKS_FIELDS,
  PREVIOUSPOLICIES_FIELDS,
  RATING_ATTRIBUTES_FIELDS,  
  RATING_ERRORS_FIELDS,
  CUSTOM_ERRORS_FIELDS,
  POLICY_RISK_FIELDS
} from './fragments';

export const START_CANCELLATION = gql`
mutation StartCancellation($policyNumber: String, $transactionType: String) {
  startCancellation(PolicyNumber: $policyNumber, TransactionType: $transactionType) {
    id
    AccountId
    QuoteNumber
    IsPolicyBind
    IsInForce
    IsRenewed
    PolicyNumber
    PolicyTerm {
      Value
      ValueType
    }
    EffectiveDate
    ExpirationDate
    PolicyStatus
    CurrentVersion
    CurrentVersionEffectiveFrom
    PayMode
    InceptionTime
    SignatureType
    UnderwritingTier
    FinancialTier
    ForceRetiering
    ActivityCode
    UMAddedReducedIndex
    PreferredAgency
    BindDate
    QuoteDate
    QuoteExpDate
    RenewalTerm
    RenewalQuoteID
    IsOOS
    SelectStackUM
    PolicyStatusHistory {
      OldStatus
      NewStatus
      ChangedBy
      ChangedDate
    }
    NonFunctional {
      LastSubmittedPage
      Milestones
    }
    PreviousPolicies {
      IsPreviousPolicy
      PreviousPolicyNumber
      OtherCoverages
      IsPreviousClaims
      NoOfClaims
      TotalAmountClaimed
    }
    DiscountAndSurcharges {
      Name
      Type
      Amount
      IsApplied
      Value
    }
    PolicyRiskAttributes {
      FirstName
      MiddleName
      LastName
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
      EstimatedBalanceAfterCancel
      BillingAccountNumber
      CurrentPolicyBalance
      DropboxSignatureRequestID
      CancellationCount
      ReinstatementCount
      EndorsementCount
      InstallmentDueDate
      CurrentInstallmentAmount
    }
    InsuredAccount {
      Type
      CreationDate
      Suffix
      UserName
      FirstName
      MiddleName
      LastName
      DisplayName
      DOB
      BankDetails {
        AccountName
        BankName
        BranchName
        AccountType
        RoutingNo
      }
      Address {
        Number
        AddressType
        IsManual
        Description
        AddressLine1
        AddressLine2
        AptSuite
        City
        County
        CountyCode
        State
        PoBox
        Postalcode
        FormattedAddress
        UnFormattedAddress
        AdministrationArea1
        AdministrationArea2
        Locality
        Lat
        Long
        Name
        Premise
        Status
        Territory
        Business
        PlaceId
        AptSuiteLot
        Street
        StreetName
      }
      BusinessInfo {
        BusinessType
        YearsInBusiness
        IncorporationAge
        BusinessName
        DisplayName
        RegistrationNumber
        BusinessStruct
        SpecialRisk
        NoOfOwners
        FullTimeEmployees
        PartTimeEmployees
        Website
        IndustryType
        BusinessDecsription
        AnnualRevenue
        NumberOFLocations
        Locations {
          NickName
          LocationNumber
          IsValid
          Status
          Type
          Address {
            Number
            AddressType
            IsManual
            Description
            AddressLine1
            AddressLine2
            AptSuite
            City
            County
            CountyCode
            State
            PoBox
            Postalcode
            FormattedAddress
            UnFormattedAddress
            AdministrationArea1
            AdministrationArea2
            Locality
            Lat
            Long
            Name
            Premise
            Status
            Territory
            Business
            PlaceId
            AptSuiteLot
            Street
            StreetName
          }
        }
      }
      IsAuthorizeForReports
      IsAuthorizationforConsumerRatingInformation
      IsAuthorizeForCreditScore
      CreditScore {
        Score
        ScoreDescription
        StatusCode
        Message
        NeedApiCall
      }
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
    }
    JointPolicyHolders {
      FirstName
      MiddleName
      LastName
      DateOfBirth
      InsuredType
      Age {
        Value
        ValueType
      }
      Occupation
      IsHighProfile
      IsAddressSameAsRisk
      Address {
        Number
        AddressType
        IsManual
        Description
        AddressLine1
        AddressLine2
        AptSuite
        City
        County
        CountyCode
        State
        PoBox
        Postalcode
        FormattedAddress
        UnFormattedAddress
        AdministrationArea1
        AdministrationArea2
        Locality
        Lat
        Long
        Name
        Premise
        Status
        Territory
        Business
        PlaceId
        AptSuiteLot
        Street
        StreetName
      }
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
    }
    Audit {
      CreatedBy
      CreatedOn
      DeletedOn
      LastUpdatedBy
      LastUpdatedOn
    }
    ExternalRefrences {
      ReferenceNumber
      ReferenceTarget
      Status
    }
    Payments {
      LastName
      FirstName
      OrderID
      TransactionType
      TransactionID
      TransactionDate
      TransactionStatus
      TransactionAmount
      CardDetails {
        Type
        CardNumber
        Expiry
        CVVCode
        LastFourDigits
      }
      BankDetails {
        AccountName
        BankName
        BranchName
        AccountType
        RoutingNo
      }
    }
    Attributes {
      AppSource
      Carrier
      Client
      Coverholder
      Lob
      State
      Product
      RaterVersion
      IsBridge
      IsInEligible
      IsNonOwnerPolicy
      FullCoverage
      TotalViolationPoints
      IsTestPolicy
      RenewalConfigurations {
        BeforeForAgent {
          Value
          ValueType
        }
        AfterForAgent {
          Value
          ValueType
        }
        BeforeForUnderwriter {
          Value
          ValueType
        }
        AfterForUnderwriter {
          Value
          ValueType
        }
      }
      QuoteValidity {
        Value
        ValueType
      }
    }
    PolicyCoverages {
      Coverages {
        Carrier
        Name
        Description
        Type
        SettlementType
        Value
        Limit
        LimitAmount
        Deductible
        IsApplicable
        IsSelected
        IsMandatory
        Status
      }
    }
    Payplan {
      DownPaymentPercentage
      DownPaymentCode
      DownPaymentDueDays
      DownPaymentAmount
      PayInFull
      NoOfInstallments
      MoreThanDPAmount
      IsSelected
      PPDescription
      Installments {
        InstallmentNumber
        BillingPlan
        DownPay
        Payments
        Date
        IsSelected
      }
    }
    FeesAndTaxes {
      Code
      Description
      Type
      IsOverride
      Status
      Value
      ValueType
      Amount
      AnnualAmount
      IsProRated
    }
    TotalPremium {
      BasicPremium
      Surcharge
      Discount
      MinPremium
      EffectivePremium
      AnnualPremium
      PriorAnnualPremium
      EffectivePremiumWithFeesAndTaxes
      AnnualPremiumWithFeesAndTaxes
      OOSPremium
    }
    Forms {
      Status
      FormName
      FormDesc
      Sequence
      FormType
      Template
      IsMandatory
      IsChecked
      AcordCode
      File
      Dmspath
    }
    Transaction {
      Number
      Date
      EffectiveDate
      EffectiveTime
      Type
      Status
      RequestedBy
      RequestedById
      IsOutOfSequence
      PremiumType
      PolicyVersion
      FileType
      FileName
      File
      Remarks
      HoldRemarks
      RejectRemarks
      Reason
      ReasonId
      MEP
      SCR
      Verification {
        IsInsuredESignVerified
        IsAgentESignVerified
        IsEmailVerified
        IsOTPVerified
        InsuredOTP
      }
      TransactionStatusHistory {
        OldStatus
        NewStatus
        ChangedBy
        ChangedDate
      }
      RenewalOffers {
        RenewalOfferId
        CurrentPremium
        RenewalPremium
        IsUpdateRenewalPremium
        RenewalOfferFlags {
          CreatedOn
          UpdatedOn
          CreatedBy
          UpdatedBy
          EmailSentFlag
        }
      }
    }
    Underwriting {
      Code
      Key
      Value
      Remark
      Optional {
        Value
        label
      }
    }
    UnderwritingNew {
      IsPhysicalImpairment
      PhysicalImpairment
      HaveAllDriversListed
      ReasonAllDriversNotListed
      HaveAllResidentsDisclosed
      ReasonAllResidentsNotDisclosed
      IsMemberOfArmedForces
      RemarkOnMemberOfArmedForces
      AgreeToNotifyDrivingStatus
      AgreementOnUndisclosedDriver
      IsUnrepairedDamage
      DescribeUnrepairedDamage
      HasListedAllVehicles
      DescribeIfNotAllVehiclesListed
      HasAllVehiclesTitledToInsured
      DescribeIfNotAllVehiclesTitled
      NameOnTitle
      InspectedByAgent
      DescribeIfNotInspectedByAgent
      GaragedInState
      DescribeIfNotGaragedInState
      IsProvidingTransportServices
      DescribeTransportServices
      IsUsedForDeliveryNetwork
      DescribeIfUsedForDeliveryNetwork
      IsDriverConvictedOfFelony
      DescribeIfDriverConvictedOfFelony
    }
    Risks {
      Vehicles {
        UnitId
        UnitNumber
        Name
        UnitType
        Status
        IsDeleted
        IsNewlyAdded
        AdditionalParties {
          Status
          Name
          ReferenceNumber
          IsPayee
          PartyType
          InterestType
          CreatedOn
          DeletedOn
          Address {
            Number
            AddressType
            IsManual
            Description
            AddressLine1
            AddressLine2
            AptSuite
            City
            County
            CountyCode
            State
            PoBox
            Postalcode
            FormattedAddress
            UnFormattedAddress
            AdministrationArea1
            AdministrationArea2
            Locality
            Lat
            Long
            Name
            Premise
            Status
            Territory
            Business
            PlaceId
            AptSuiteLot
            Street
            StreetName
          }
          Communications {
            Type
            SubType
            Value
            Status
            AcceptText
          }
        }
        VehicleRiskAttributes {
          ClassificationType
          SecondaryUse
          SecondaryUsePercent
          VehicleType
          VIN
          Year
          VehicleAge
          Make
          Model
          OwnedOrLeased
          BusinessUseClass
          SizeClass
          GROSSCOMBWEIGHT
          RADIUSCLASSTYPE
          VEHPRICE
          PASSIVERESTR
          VEHYEAR
          ANTILOCKBRAKES
          COSTTYPE
          FARTHESTLOCCITY
          FARTHESTLOCCOUNTY
          FARTHESTLOCSTATE
          FARTHESTLOC
          ISVEHICLEUPLOADED
          COMPDED
          COLLDED
          MPDED
          HASPD
          HASMP
          TEMPLATENAME
          UWREFMSG
          GARAGELOC
          HASRENTAL
          CSLLIMIT
          LIABDED
          UMTYPE
          UMDED
          UMLIMIT
          PrimaryGaragingLocation {
            Number
            AddressType
            IsManual
            Description
            AddressLine1
            AddressLine2
            AptSuite
            City
            County
            CountyCode
            State
            PoBox
            Postalcode
            FormattedAddress
            UnFormattedAddress
            AdministrationArea1
            AdministrationArea2
            Locality
            Lat
            Long
            Name
            Premise
            Status
            Territory
            Business
            PlaceId
            AptSuiteLot
            Street
            StreetName
          }
          AdditionalInterestDetails {
            DetailNo
            Type
            Name
            Address
            City
            State
            Postalcode
            AptSuite
            IsDeleted
          }
          HasAdditionalInterestDetails
          SymbolOTC
          SymbolColl
          SymbolLiab
          SymbolMP
          OTCDeductible
          CollDeductible
          IsGaragingSameAsMailing
          IncludePunitiveDamages
          IsDNI
          AnnualMileage
          BodyStyle
          MechanicalDesc
          IsNonOwnerPolicy
          VerifiedVIN
          Towing
          Rental
          Use
          AirbagDisc
          AssignedDriver
          SoftDelete
          VehicleLoadCapacity
          IsBusinessUse
        }
        Coverages {
          Carrier
          Name
          Description
          Type
          SettlementType
          Value
          Limit
          LimitAmount
          Deductible
          IsApplicable
          IsSelected
          IsMandatory
          Status
        }
        PremiumFactors {
          Name
          Status
          Type
          Description
          IsApplicable
          IsSelected
          IsMandatory
          Rate
          Limit
          LimitAmount
          Deductible
          Premium
          EffectivePremium
          AnnualPremium
          PremiumDifference
          Factor {
            Name
            Type
            Description
            Rate
            Limit
            LimitAmount
            Premium
            Status
            IsApplicable
            IsSelected
            IsMandatory
            Deductible
            EffectivePremium
            AnnualPremium
          }
        }
        Premium {
          BasicPremium
          Surcharge
          Discount
          MinPremium
          EffectivePremium
          AnnualPremium
          EffectivePremiumWithFeesAndTaxes
          AnnualPremiumWithFeesAndTaxes
        }
        Audit {
          CreatedBy
          CreatedOn
          DeletedOn
          LastUpdatedBy
          LastUpdatedOn
        }
      }
      Drivers {
        UnitId
        UnitNumber
        Name
        UnitType
        Status
        IsDeleted
        IsNewlyAdded
        DriverRiskAttributes {
          Type
          PrevType
          FirstName
          MiddleName
          LastName
          Suffix
          DOB
          Age
          Experience
          LicenseNumber
          Violations
          IsUSCitizen
          Occupation
          OtherOccupation
          FilingStatusCode
          Fillings {
            Fillings
            Date
            Reason
            FilingCd
            FilingStatusCd
          }
          FilingCode
          LicenseDate
          State
          HadTrainingCourse
          IsMilitary
          MilitaryRank
          HadDUIDWI
          DriverCourseCompletedDate
          CanInsureOperate
          LicenseStatus
          IsGoodStudentDiscountApplicable
          MaritalStatus
          Gender
          Violation {
            ViolationNumber
            Date
            Type
            HadAccident
            ConvictionDate
            PJC
            TotalPoints
            SISCode
            AccidentViolationDisputeCode
            Dispute
            DisputeReason
            Source
            IsNewlyAdded
          }
          RelationToApplicant
          IsDNI
          IsEditing
          SSN
          AgeWhenFirstLicensed
          MVRCount
          MVRViolationStatus
          IsVerifiedBy
        }
        Coverages {
          Carrier
          Name
          Description
          Type
          SettlementType
          Value
          Limit
          LimitAmount
          Deductible
          IsApplicable
          IsSelected
          IsMandatory
          Status
        }
        PremiumFactors {
          Name
          Status
          Type
          Description
          IsApplicable
          IsSelected
          IsMandatory
          Rate
          Limit
          LimitAmount
          Deductible
          Premium
          EffectivePremium
          AnnualPremium
          PremiumDifference
          Factor {
            Name
            Type
            Description
            Rate
            Limit
            LimitAmount
            Premium
            Status
            IsApplicable
            IsSelected
            IsMandatory
            Deductible
            EffectivePremium
            AnnualPremium
          }
        }
        Premium {
          BasicPremium
          Surcharge
          Discount
          MinPremium
          EffectivePremium
          AnnualPremium
          EffectivePremiumWithFeesAndTaxes
          AnnualPremiumWithFeesAndTaxes
        }
        Audit {
          CreatedBy
          CreatedOn
          DeletedOn
          LastUpdatedBy
          LastUpdatedOn
        }
      }
    }
    Rules {
      Action
      MatchingRules {
        Type
        Description
        Isfulfilled
        Status
        Remark
        Reason
      }
    }
    UnderWriter {
      Client
      Code
      Name
      Status
      Reference
      Products
      UWAttributes {
        UWOffice
        ContractNumber
        AccountExecCode
      }
      Address {
        Number
        AddressType
        IsManual
        Description
        AddressLine1
        AddressLine2
        AptSuite
        City
        County
        CountyCode
        State
        PoBox
        Postalcode
        FormattedAddress
        UnFormattedAddress
        AdministrationArea1
        AdministrationArea2
        Locality
        Lat
        Long
        Name
        Premise
        Status
        Territory
        Business
        PlaceId
        AptSuiteLot
        Street
        StreetName
      }
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
    }
    PriorInsurances {
      IsCurrentlyInsured
      CompanyName
      OtherCompanyName
      EffectiveDate
      ExpirationDate
      Premium
      Status
    }
    Agency {
      Client
      Code
      Name
      Status
      Reference
      Products
      Address {
        Number
        AddressType
        IsManual
        Description
        AddressLine1
        AddressLine2
        AptSuite
        City
        County
        CountyCode
        State
        PoBox
        Postalcode
        FormattedAddress
        UnFormattedAddress
        AdministrationArea1
        AdministrationArea2
        Locality
        Lat
        Long
        Name
        Premise
        Status
        Territory
        Business
        PlaceId
        AptSuiteLot
        Street
        StreetName
      }
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
    }
    Agent {
      Client
      Code
      Name
      Status
      Reference
      Products
      Address {
        Number
        AddressType
        IsManual
        Description
        AddressLine1
        AddressLine2
        AptSuite
        City
        County
        CountyCode
        State
        PoBox
        Postalcode
        FormattedAddress
        UnFormattedAddress
        AdministrationArea1
        AdministrationArea2
        Locality
        Lat
        Long
        Name
        Premise
        Status
        Territory
        Business
        PlaceId
        AptSuiteLot
        Street
        StreetName
      }
      Communications {
        Type
        SubType
        Value
        Status
        AcceptText
      }
    }
    AgentCommission {
      Value
      ValueType
    }
    Claims {
      Status
      ClaimSequence
      IsUnrepairedDamage
      DateofLoss
      PaidAmount
      ReserveAmount
      IncidentType
      CoverageType
      ClaimantName
      UnitId
      Remark
    }
    PremiumFactors {
      Name
      Status
      Type
      Description
      IsApplicable
      IsSelected
      IsMandatory
      Rate
      Limit
      LimitAmount
      Deductible
      Premium
      EffectivePremium
      AnnualPremium
      PremiumDifference
      Factor {
        Name
        Type
        Description
        Rate
        Limit
        LimitAmount
        Premium
        Status
        IsApplicable
        IsSelected
        IsMandatory
        Deductible
        EffectivePremium
        AnnualPremium
      }
    }
    Premium {
      BasicPremium
      Surcharge
      Discount
      MinPremium
      EffectivePremium
      AnnualPremium
      EffectivePremiumWithFeesAndTaxes
      AnnualPremiumWithFeesAndTaxes
    }
    ReconciliationFlags {
      LiabilityPolicy
      ClueCount
      ClueVioationStatus
    }
			OOS {
				TotalPremium {
					BasicPremium
					Surcharge
					Discount
					MinPremium
					EffectivePremium
					AnnualPremium
					PriorAnnualPremium
					EffectivePremiumWithFeesAndTaxes
					AnnualPremiumWithFeesAndTaxes
					OOSPremium
				}
				FeesAndTaxes {
					Code
					Description
					Type
					IsOverride
					Status
					Value
					ValueType
					Amount
					AnnualAmount
					IsProRated
				}
			}
  }
}
`;

export const RATE_ENDORSEMENT = gql`
${CORE_POLICY_FIELDS}
${UNDERWRITTING_FIELDS}
${TRANSACTION_FIELDS}
${PREMIUM_FACTORS_FIELDS}
${PREMIUM_FIELDS}
${TOTAL_PREMIUM_FIELDS}
${POLICY_COVERAGES_FIELDS}
${ATTRIBUTES_FIELDS}
${AUDIT_FIELDS}
${EXTERNALREFERENCES_FIELDS}
${DISCOUNT_SURCHARGE_FIELDS}
${RULES_FIELDS}
${FORMS_FIELDS}
${FEES_TAXES_FIELDS}
${INSURED_ACCOUNT_FIELDS}
${RISKS_FIELDS}
${PREVIOUSPOLICIES_FIELDS}
${NON_FUNCTIONAL_FIELDS}
${RATING_ATTRIBUTES_FIELDS}
${RATING_ERRORS_FIELDS}
${CUSTOM_ERRORS_FIELDS}
${POLICY_RISK_FIELDS}
mutation ($input: inpPolicy) {
  rateEndorsement(input: $input) {
    ...CorePolicyFields
    ...UnderwritingFields
    ...TransactionFields
    ...PremiumFactorsFields
    ...PremiumFields
    ...TotalPremiumFields
    ...PolicyCoverageFields
    ...AttributesFields
    ...AuditFields
    ...DiscountSurchargeFields
    ...RulesFields
    ...FormsFields
    ...FeesAndTaxesFields
    ...ExternalReferencesFields
    ...InsuredAccountFields
    ...RisksFields
    ...NonFunctionalFields
    ...PreviousPoliciesFields
    ...RatingAttributesFields
    ...RatingErrorsFields
    ...CustomErrorsFields
    ...PolicyRiskFields
  }
}
`;

