import React from "react";
import UploadDocumentFunctionalComp from "./uploaddocumentfunctional";
import { getFilesListFromDMS } from "./utilities/helpers";

const policy = {
    "id": "a8c5374d-3517-40d6-a77f-8b6ec58a8852",
    "AccountId": "Underwriter",
    "QuoteNumber": "SDRHHO3OR230040",
    "IsInForce": false,
    "IsPolicyBind": false,
    "IsRenewed": false,
    "PolicyNumber": "SDRHHO3OR230454",
    "EffectiveDate": "2023-07-20",
    "ExpirationDate": "2024-07-20",
    "BindDate": "2022-01-01",
    "QuoteDate": "2023-07-21",
    "PolicyStatus": "Submission",
    "Agency": {
        "Client": "ROTHERT",
        "Code": "101001",
        "Name": "OR Test Agency",
        "Status": "Active",
        "Products": [
            "SDRHHO3OR"
        ],
        "Reference": [
            "13689"
        ],
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "ksharma@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "ksharma@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "ksharma@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "ksharma@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "ksharma@cogitate.us"
            }
        },
        "Address": {
            "Postalcode": null,
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Locality": null,
            "Lat": null,
            "Premise": null,
            "Description": null,
            "CountyCode": null,
            "County": "Multnomah County",
            "City": "Portland",
            "Business": null,
            "AdministrationArea2": null,
            "AdministrationArea1": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "PoBox": null,
            "AddressLine1": null,
            "AddressLine2": null,
            "AptSuite": null,
            "Territory": null,
            "State": "OR",
            "Zip": "97213",
            "Country": "US",
            "AddressType": "M",
            "CountryCode": "US",
            "Addr2": "5234 NE Sandy Blvd., Portland, OR 97213",
            "IsManual": null
        }
    },
    "Agent": {
        "Client": "ROTHERT",
        "Code": "13690",
        "Name": "Paul Rothert",
        "Status": "Active",
        "Products": [
            "SDRHHO3OR"
        ],
        "Reference": [
            "101001"
        ],
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "npatidar@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "ksharma@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "ksharma@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "ksharma@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "ksharma@cogitate.us"
            }
        },
        "Address": {
            "Postalcode": null,
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Locality": null,
            "Lat": null,
            "Premise": null,
            "Description": null,
            "CountyCode": null,
            "County": "Multnomah County",
            "City": "Portland",
            "Business": null,
            "AdministrationArea2": null,
            "AdministrationArea1": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "PoBox": null,
            "AddressLine1": null,
            "AddressLine2": null,
            "AptSuite": null,
            "Territory": null,
            "State": "OR",
            "Zip": "97213",
            "Country": "US",
            "AddressType": "M",
            "CountryCode": "US",
            "Addr2": "5234 NE Sandy Blvd., Portland, OR 97213",
            "IsManual": null
        }
    },
    "UnderWriter": {
        "Client": "ROTHERT",
        "Code": "13689",
        "Name": "Mark Rothert",
        "Status": "Active",
        "Products": [
            "SDRHHO3OR"
        ],
        "Reference": [
            "101001"
        ],
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "npatidar@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "ksharma@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "ksharma@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "ksharma@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "ksharma@cogitate.us"
            }
        },
        "Address": {
            "Postalcode": null,
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Locality": null,
            "Lat": null,
            "Premise": null,
            "Description": null,
            "CountyCode": null,
            "County": "Multnomah County",
            "City": "Portland",
            "Business": null,
            "AdministrationArea2": null,
            "AdministrationArea1": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "PoBox": null,
            "AddressLine1": null,
            "AddressLine2": null,
            "AptSuite": null,
            "Territory": null,
            "State": "OR",
            "Zip": "97213",
            "Country": "US",
            "AddressType": "M",
            "CountryCode": "US",
            "Addr2": "5234 NE Sandy Blvd., Portland, OR 97213",
            "IsManual": null
        },
        "UWAttributes": null
    },
    "NonFunctional": {
        "LastSubmittedPage": "/Personal/HomeOwners/Application/Coverage",
        "Milestones": [
            0,
            1,
            2,
            3
        ],
        "InsuredOTP": ""
    },
    "Underwriting": {
        "IsAnyBusinessOnPremise": "false",
        "AnyResidenceEmployees": "false",
        "NoOfPartTimeEmployees": "",
        "NoOfFullTimeEmployees": "",
        "IsPropertyInHazardArea": "false",
        "AnyOtherResidence": "false",
        "IsAnyOtherInsuranceWithCompany": "false",
        "ListPolicyNumber": "",
        "AnyCoverageHistoryInLastThreeYear": "false",
        "HadForeclosureRepossessionOrBankruptcy": "false",
        "ReasonForForeclosureRepossessionOrBankruptcy": "",
        "StatusForForeclosureRepossessionOrBankruptcy": "1",
        "DateClosedStatusForForeclosureRepossessionOrBankruptcy": "",
        "IsApplicantDelinquentOnMortgageOrTaxPayment": "false",
        "IsExoticAnimalOrPet": "false",
        "IsAnimalWithBiteHistory": "false",
        "AddTypeOfAnimalBox": "",
        "AnimalOrPetBreed": "",
        "IsLakeOrPondOrDockOnPremises": "false",
        "DistanceToTidalWater": "3",
        "IsPropertyMoreThanFiveAcres": "false",
        "NoOfAcres": "",
        "DescribeLandUse": "",
        "OtherStructureOnPremise": "false",
        "DescribeStructureOnPremise": "",
        "IsBuildingRetrofittedForEarthQuake": "false",
        "IsAnyCriminalHistory": "false",
        "IsAnyExistingDamages": "false",
        "IsUnderRenovationOrReconstruction": "false",
        "ContractorName": "",
        "CompletionDate": "",
        "CompletedValue": "",
        "IsHouseForSale": "false",
        "IsAnyCommercialOrNonResidentialProperty": "false",
        "IsTrampolineOnPremise": "false",
        "IsStructureConverted": "false",
        "IsAnySwimingPool": "false",
        "IsSwimingPoolEnclosed": "false",
        "IsAnyDivingBoardsPresent": "false",
        "IsAnySlidesPresent": "false",
        "IsThePropertyCurrentlyInsured": "false",
        "PriorInsuranceCompany": "",
        "PriorInsurancePolicyNumber": "",
        "PriorInsuranceExpirationDate": ""
    },
    "Transaction": {
        "Number": 0,
        "Date": "",
        "EffectiveDate": "",
        "Type": "Application",
        "Status": "Rated",
        "RequestedBy": "",
        "RequestedById": "",
        "PremiumType": "",
        "PolicyVersion": "",
        "FileType": "",
        "FileName": "",
        "File": "",
        "IsOutOfSequence": false,
        "Remarks": "",
        "Reason": "",
        "MEP": "",
        "Verification": {
            "IsInsuredESignVerified": false,
            "IsAgentESignVerified": false,
            "IsEmailVerified": false,
            "IsOTPVerified": false,
            "InsuredOTP": ""
        },
        "TransactionStatusHistory": {
            "OldStatus": "",
            "NewStatus": "",
            "ChangedBy": "",
            "ChangedDate": ""
        },
        "RenewalOffers": {
            "RenewalOfferId": "",
            "CurrentPremium": 0,
            "RenewalPremium": 0,
            "IsUpdateRenewalPremium": false,
            "RenewalOfferFlags": {
                "CreatedOn": "",
                "UpdatedOn": "",
                "CreatedBy": "",
                "UpdatedBy": "",
                "EmailSentFlag": false
            }
        }
    },
    "Attributes": {
        "Client": "ROTHERT",
        "AppSource": "",
        "Carrier": "SD",
        "Lob": "HO3",
        "State": "OR",
        "Product": "SDRHHO3OR",
        "RaterVersion": "1.0.0.0",
        "Coverholder": "RH",
        "IsMasterPolicy": true,
        "MasterReferenceNumber": "",
        "IsTestPolicy": false,
        "NoOfClaims": "0",
        "IsCoverageSaved": true,
    },
    "InsuredAccount": {
        "Type": "",
        "CreationDate": "",
        "UserName": "",
        "FirstName": "Test",
        "MiddleName": "Test",
        "LastName": "Test",
        "DisplayName": "Test Test Test",
        "HasJointPolicyHolder": "false",
        "BankDetails": {
            "AccountName": "",
            "BankName": "",
            "BranchName": "",
            "AccountType": "",
            "RoutingNo": ""
        },
        "Communications": [
            {
                "Type": "PhNo",
                "SubType": "Primary",
                "Value": "1111111111",
                "Status": ""
            },
            {
                "Type": "Email",
                "SubType": "Primary",
                "Value": "test@gmail.com",
                "Status": ""
            }
        ],
        "BusinessInfo": {
            "BusinessType": "",
            "YearsInBusiness": 0,
            "IncorporationAge": "",
            "BusinessName": "",
            "DisplayName": "",
            "RegistrationNumber": "",
            "BusinessStruct": "",
            "SpecialRisk": "",
            "NoOfOwners": 0,
            "FullTimeEmployees": 0,
            "PartTimeEmployees": 0,
            "Website": "",
            "IndustryType": "",
            "BusinessDecsription": "",
            "AnnualRevenue": 0,
            "NumberOFLocations": 0,
            "Locations": [
                {
                    "NickName": "",
                    "LocationNumber": 0,
                    "Type": "M",
                    "IsValid": false,
                    "Status": "",
                    "Address": {
                        "Postalcode": "77843",
                        "PlaceId": "",
                        "Number": 0,
                        "Name": "",
                        "Long": "",
                        "Locality": "",
                        "Lat": "",
                        "Premise": "",
                        "Description": "",
                        "CountyCode": "",
                        "County": "",
                        "City": "College Station",
                        "Business": "",
                        "AdministrationArea2": "",
                        "AdministrationArea1": "",
                        "StreetName": "",
                        "FormattedAddress": "",
                        "UnFormattedAddress": "400 Bizzell Street , College Station, OR, 77843",
                        "Status": "",
                        "PoBox": "",
                        "AddressLine1": "400 Bizzell Street",
                        "AddressLine2": "",
                        "AptSuite": "",
                        "Territory": "",
                        "State": "OR",
                        "Zip": "",
                        "Country": "",
                        "AddressType": "M",
                        "CountryCode": "",
                        "Addr2": "",
                        "IsManual": true
                    }
                }
            ]
        },
        "OtherDetails": {
            "DateOfBirth": "2005-07-12",
            "Occupation": "Nothing",
            "ApplicantEmployerName": "Test",
            "ApplicantEmployerAddress": {
                "Postalcode": "",
                "PlaceId": "",
                "Number": 0,
                "Name": "",
                "Long": "",
                "Locality": "",
                "Lat": "",
                "Premise": "",
                "Description": "",
                "CountyCode": "",
                "County": "",
                "City": "",
                "Business": "",
                "AdministrationArea2": "",
                "AdministrationArea1": "",
                "StreetName": "",
                "FormattedAddress": "",
                "UnFormattedAddress": "",
                "Status": "",
                "PoBox": "",
                "AddressLine1": "",
                "AddressLine2": "",
                "AptSuite": "",
                "Territory": "",
                "State": "",
                "Zip": "",
                "Country": "",
                "AddressType": "M",
                "CountryCode": "",
                "Addr2": "",
                "IsManual": false
            }
        }
    },
    "Risks": {
        "Properties": [
            {
                "PropertyAge": 0,
                "UnitId": 1,
                "UnitNumber": "1",
                "Name": "",
                "UnitType": "P",
                "Status": "",
                "Premium": {
                    "BasicPremium": null,
                    "Surcharge": 0,
                    "Discount": -191.431275,
                    "MinPremium": null,
                    "AnnualPremium": 1000,
                    "EffectivePremium": 1000,
                    "AnnualPremiumWithFeesAndTaxes": null,
                    "EffectivePremiumWithFeesAndTaxes": null
                },
                "PremiumFactors": [
                    {
                        "Name": "",
                        "Status": "InActive",
                        "Type": "",
                        "Description": "",
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": null,
                        "LimitAmount": null,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "",
                            "Type": "",
                            "Description": "",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": null
                        }
                    },
                    {
                        "Name": "LiabPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Liability Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 100000,
                        "LimitAmount": 100000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "LiabPrem",
                            "Type": "",
                            "Description": "Liability Premium",
                            "Rate": 0,
                            "Limit": 100000,
                            "LimitAmount": 100000,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "MedPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Medical Payment Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 1000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "MedPrem",
                            "Type": "",
                            "Description": "Medical Payment Premium",
                            "Rate": 0,
                            "Limit": 1000,
                            "LimitAmount": 1000,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "LAPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Loss Assessment Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 1000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "LAPrem",
                            "Type": "",
                            "Description": "Loss Assessment Premium",
                            "Rate": 0,
                            "Limit": 1000,
                            "LimitAmount": 1000,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "OLPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Ordinance and Law Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 10,
                        "LimitAmount": 10,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "OLPrem",
                            "Type": "",
                            "Description": "Ordinance and Law Premium",
                            "Rate": 0,
                            "Limit": 10,
                            "LimitAmount": 10,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "ClaimRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Claim Loss Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "ClaimRate",
                            "Type": "",
                            "Description": "Claim Loss Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "ConstructionRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Construction Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "ConstructionRate",
                            "Type": "",
                            "Description": "Construction Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "FireAlarmRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Fire Alarm Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "FireAlarmRate",
                            "Type": "",
                            "Description": "Fire Alarm Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "BurglarAlarmRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Burglar Alarm Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "BurglarAlarmRate",
                            "Type": "",
                            "Description": "Burglar Alarm Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "SprinklerRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Sprinkler Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": -2,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "SprinklerRate",
                            "Type": "",
                            "Description": "Sprinkler Surcharge",
                            "Rate": -2,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "YearBuiltRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Year Built Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "YearBuiltRate",
                            "Type": "",
                            "Description": "Year Built Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "ERCRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Extended RC Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "ERCRate",
                            "Type": "",
                            "Description": "Extended RC Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "OccRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Occupancy Rate Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "OccRate",
                            "Type": "",
                            "Description": "Occupancy Rate Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "DedRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Deductible Rate Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "DedRate",
                            "Type": "",
                            "Description": "Deductible Rate Surcharge",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "IncCovCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Increased Cov C Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "IncCovCPrem",
                            "Type": "",
                            "Description": "Increased Cov C Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "RCCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Replacement Cost Contents Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "RCCPrem",
                            "Type": "",
                            "Description": "Replacement Cost Contents Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "PIPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Personal Injury Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "PIPrem",
                            "Type": "",
                            "Description": "Personal Injury Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "SCCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Special Computer Coverage Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "SCCPrem",
                            "Type": "",
                            "Description": "Special Computer Coverage Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "SPPPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Special Personal Property Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "SPPPrem",
                            "Type": "",
                            "Description": "Special Personal Property Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "IDFraudPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Identity Fraud Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "IDFraudPrem",
                            "Type": "",
                            "Description": "Identity Fraud Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "MechBrPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Mechanical Breakdown Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "MechBrPrem",
                            "Type": "",
                            "Description": "Mechanical Breakdown Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "WaterBackupPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Water Backup Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "WaterBackupPrem",
                            "Type": "",
                            "Description": "Water Backup Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "BRExtPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Builder Risk Extended Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "BRExtPrem",
                            "Type": "",
                            "Description": "Builder Risk Extended Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "TOBMPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Theft Of Building Material Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "TOBMPrem",
                            "Type": "",
                            "Description": "Theft Of Building Material Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "Base Premium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Base Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 175,
                        "EffectivePremium": 175,
                        "PremiumDifference": 175,
                        "Factor": {
                            "Name": "Base Premium",
                            "Type": "",
                            "Description": "Base Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 175,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "PCPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Protection Class Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 1,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "PCPremium",
                            "Type": "",
                            "Description": "Protection Class Premium",
                            "Rate": 1,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "IncLimPremium",
                        "Status": "Active",
                        "Type": "DIS",
                        "Description": "Increased Limit Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": -0.093893,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": -191.431275,
                        "EffectivePremium": -191.431275,
                        "PremiumDifference": -191.431275,
                        "Factor": {
                            "Name": "IncLimPremium",
                            "Type": "DIS",
                            "Description": "Increased Limit Premium",
                            "Rate": -0.093893,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": -191.431275,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "SurchargePremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Surcharge Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0.98,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0.32862499999999883,
                        "EffectivePremium": 0.32862499999999883,
                        "PremiumDifference": 0.32862499999999883,
                        "Factor": {
                            "Name": "SurchargePremium",
                            "Type": "",
                            "Description": "Surcharge Premium",
                            "Rate": 0.98,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0.32862499999999883,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "WFPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "WildFire Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 1,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "WFPremium",
                            "Type": "",
                            "Description": "WildFire Premium",
                            "Rate": 1,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "MinPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Minimum Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 1016.10265,
                        "EffectivePremium": 1016.10265,
                        "PremiumDifference": 1016.10265,
                        "Factor": {
                            "Name": "MinPremium",
                            "Type": "",
                            "Description": "Minimum Premium",
                            "Rate": 0,
                            "Limit": 1000,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 1016.10265,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    },
                    {
                        "Name": "RoundFactor",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Round Factor Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "Factor": {
                            "Name": "RoundFactor",
                            "Type": "",
                            "Description": "Round Factor Premium",
                            "Rate": 0,
                            "Limit": 0,
                            "LimitAmount": 0,
                            "Deductible": 0,
                            "Premium": 0,
                            "EffectivePremium": 0,
                            "IsApplicable": false,
                            "IsSelected": false,
                            "IsMandatory": false,
                            "Status": ""
                        }
                    }
                ],
                "Coverages": [
                    {
                        "Id": "1",
                        "Name": "coverageA",
                        "Description": "Coverage A - Dwelling",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "123",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "2",
                        "Name": "coverageB",
                        "Description": "Coverage B - Other Structures",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "12",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "3",
                        "Name": "coverageC",
                        "Description": "Coverage C - Personal Property",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "62",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "4",
                        "Name": "coverageD",
                        "Description": "Coverage D - Loss of Use",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "25",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "5",
                        "Name": "coverageE",
                        "Description": "Coverage E - Liability",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "100000",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "6",
                        "Name": "coverageF",
                        "Description": "Coverage F - Medical Payments",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1000",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "7",
                        "Name": "lossAssessment",
                        "Description": "Loss Assessment",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1000",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "8",
                        "Name": "ordinanceOrLaw",
                        "Description": "Ordinance or Law",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "10",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "9",
                        "Name": "increasedCovC",
                        "Description": "Increased Cov C Option",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "None",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "10",
                        "Name": "personalInjuryCover",
                        "Description": "Personal Injury Cover",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "11",
                        "Name": "specialComputerCoverage",
                        "Description": "Special Computer Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "12",
                        "Name": "replacmentCostContents",
                        "Description": "Replacement Cost Contents",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "13",
                        "Name": "specialPersonalPropertyCoverage",
                        "Description": "Special Personal Property Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "14",
                        "Name": "waterBackup",
                        "Description": "Water Back Up",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "0",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "15",
                        "Name": "extendedReplacementCost",
                        "Description": "Extended replacement cost",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "16",
                        "Name": "identityFraudExp",
                        "Description": "Identity fraud expense",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "17",
                        "Name": "buildersRiskExtentedCoverages",
                        "Description": "Builders Risk Extended Coverages",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "18",
                        "Name": "theftOfBuildingMaterialsCoverage",
                        "Description": "Theft of Building Materials Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "19",
                        "Name": "mechanicalBreakDownCoverage",
                        "Description": "Mechanical Breakdown Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "20",
                        "Name": "allOtherPerils",
                        "Description": "All Other Perils Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1000",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "21",
                        "Name": "smokeDeductible",
                        "Description": "Smoke Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "22",
                        "Name": "theftDeductible",
                        "Description": "Theft Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "23",
                        "Name": "waterDeductible",
                        "Description": "Water Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "24",
                        "Name": "windDeductible",
                        "Description": "Wind Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "25",
                        "Name": "TIV",
                        "Description": "Total Insurable Value",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "222",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    }
                ],
                "Audit": {
                    "CreatedBy": "",
                    "CreatedOn": "",
                    "LastUpdatedBy": "",
                    "LastUpdatedOn": ""
                },
                "AdditionalParties": {
                    "MortgageeDetails": [],
                    "AdditionalInsured": [],
                    "AdditionalInterest": [],
                    "Trust": []
                },
                "PropertyRiskAttributes": {
                    "IsLLC": "false",
                    "HasSameMailingAddress": "true",
                    "OccupancyType": "Primary",
                    "CoverageStartDate": "",
                    "YearBuilt": "2004",
                    "SquareFeet": "123",
                    "ConstructionType": "Frame",
                    "ProtectionClass": "2",
                    "HydrantDistance": "200",
                    "FireStationDistance": "5",
                    "FireStationDriveDuration": "23",
                    "BrushFireDistance": "NA",
                    "NoOfStories": "1",
                    "NoOfFamilies": "1",
                    "Foundation": "Open",
                    "FireScore": "low",
                    "FireAlarm": "Local Alarm",
                    "BurglarAlarms": "None",
                    "SprinklerSystem": "Yes",
                    "ShortTermRental": "false",
                    "WeeksRentedPerYear": "",
                    "Deadbolt": "false",
                    "FireExtinguisher": "false",
                    "VisibleToNeighbours": "false",
                    "RoofType": "Tile",
                    "RoofUpdateType": "None",
                    "RoofUpdateYear": "2004",
                    "HeatingType": "None",
                    "HeatingUpdateType": "None",
                    "HeatingUpdateYear": "2004",
                    "ElectricalType": "Circuit Breakers",
                    "ElectricalUpdateType": "None",
                    "ElectricalUpdateYear": "2004",
                    "PlumbingType": "Galvanized",
                    "PlumbingUpdateType": "None",
                    "PlumbingUpdateYear": "2004",
                    "MinimumPremium": "",
                    "DsValFireScore": "6",
                    "DsValBrushFireDistance": "NA",
                    "CovBPercentageOfCovA": "9.76",
                    "CovCPercentageOfCovA": "50.41",
                    "CovDPercentageOfCovA": "20.33"
                },
                "Address": {
                    "Postalcode": "77843",
                    "PlaceId": "",
                    "Number": 0,
                    "Name": "",
                    "Long": "-96.3364411",
                    "Locality": "",
                    "Lat": "30.6187274",
                    "Premise": "",
                    "Description": "",
                    "CountyCode": "",
                    "County": "Brazos County",
                    "City": "College Station",
                    "Business": "",
                    "AdministrationArea2": "",
                    "AdministrationArea1": "",
                    "StreetName": "",
                    "FormattedAddress": "",
                    "UnFormattedAddress": "400 Bizzell Street , College Station, OR, 77843",
                    "Status": "",
                    "PoBox": "",
                    "AddressLine1": "400 Bizzell Street",
                    "AddressLine2": "",
                    "AptSuite": "",
                    "Territory": "",
                    "State": "OR",
                    "Zip": "",
                    "Country": "",
                    "AddressType": "P",
                    "CountryCode": "",
                    "Addr2": "",
                    "IsManual": true
                }
            }
        ]
    },
};

const DocumentsColumns = [
    {
        dataField: 'TransactionType',
        text: 'TRANSACTION TYPE	',
        sort: false,
        headerStyle: () => {
            return { width: "17%" };
        }
    },
    {
        dataField: 'UserName',
        text: 'User',
        sort: false,
        headerStyle: () => {
            return { width: "17%", textAlign: "center" };
        },
        customFormatter: (data) => data + "Test"
    },
    {
        dataField: 'DocumentType',
        text: 'DOCUMENT TYPE',
        sort: false,
        headerStyle: () => {
            return { width: "25%", textAlign: "center" };
        },
        // formatter: DocumentTypeFormatter
    },
    {
        dataField: 'TransactionDate',
        text: 'Uploaded / Created Date',
        sort: false,
        headerStyle: () => {
            return { width: "22%", textAlign: "center" };
        },
        // formatter: DocumentDateFormatter
    },
    {
        dataField: 'EffectiveDate',
        text: 'EFFECTIVE DATE',
        sort: false,
        headerStyle: () => {
            return { width: "17%" };
        },
        // formatter: DocumentDateFormatter,
        hidden: true
    },
    {
        dataField: 'Uri',
        text: 'FileUrl',
        sort: false,
        headerStyle: () => {
            return { width: "20%" };
        },
        hidden: true
    },
];

const functionalArgs = {
    policy: policy,
    tableCols: DocumentsColumns,
    groupColumnName: "TransactionType",
    dmsContainerName: "dms",
    useRefresh: true,
    EmailDocument: ms => new Promise(res => setTimeout(res, 2000)),
    uploadFilesToDMS: (ms, model) => new Promise(res => setTimeout(() => {
        console.log(model);
        res(true);
    }, 2000)),
    getFilesListFromDMS: async (args) => {
        
        return await getFilesListFromDMS(args, "https://dev.cogitate.us/DIEP2.DMS.API/api/GetPolicyDocList?", "Basic dGVzdDp0ZXN0VXNlclBhc3N3b3Jk");
    },
    toast: (msg, err) => {
        if (err) alert(`Error: ${msg}`); //replace alert with toast in application
        else alert(`Success: ${msg}`);
    },
    fileProps: { fileSize: 100*1024*1024, allowedFiles: ["pdf", "xlsx", "csv", "eml", "png", "jpeg", "doc", "docx", "txt", "ppt", "pptx", "xls"] },
    extras: {
        uploadDocDialogClassName: "modal-90w",
        uploadDocSize: "md",
        emailDialogClassName: "modal-30w",
        emailSize: "md",
    },
    ignoreFileView: ["xlsx"],
    hideUploadBtn: false,
    // columnList: ["Application", "Manual Upload"]
};

export default {
    title: "Design System/Functional/UploadDocuments",
    component: UploadDocumentFunctionalComp,
    argTypes: {
        policy: {
            description: "Policy to which file is to be uploaded.",
            table: {
                category: "Schema",
            },
        },
        tableCols: {
            description:
                "Column of Upload Document Table. The datafield attribute must be the one of the property of policy model.",
            table: {
                category: "Schema",
            },
        },
        loggedInUser: {
            description:
                "Current Username which will be displayed in table when file is uploaded.",
            table: {
                category: "string",
            },
        },
        groupColumnName: {
            description:
                "Datafield name of column based on which rows will be grouped. E.g: TransactionType",
            table: {
                category: "string",
            },
        },
        uploadFilesToDMS: {
            description: "Function to perform upload documents action. Is available in utilities folder of the application",
            table: {
                category: "Function",
            },
        },
        getFilesListFromDMS: {
            description: "Function to get files from dms. Is available in utilities folder of the application",
            table: {
                category: "Function",
            },
        },
        EmailDocument: {
            description: "Function to send email.",
            table: {
                category: "Function"
            }
        },
        // Optional Props
        columnList: {
            description: "Prop used to arrange documents according to passed list of groupByColumnName prop. Note: Data will be missing if groupByColumnName type for certain data is not provided. Default is [].",
            table: {
                category: "Array"
            }
        },
        hideUploadBtn: {
            description: "Prop tohide upload button. Default is false.",
            table: {
                category: "Boolean"
            }
        },
        extras: {
            description: "prop to change size of modal popup.",
            table: {
                category: "Object"
            }
        },
        updatePolicy: {
            description:
                "Optional function to update policy status after a file is uploaded based on document type.",
            table: {
                category: "Function",
            },
        },
        uploadDocumentSchema: {
            description:
                "Optional schema to be passed for providing custom form to upload file",
            table: {
                category: "Schema",
            },
        },
        uploadDataModel: {
            description: "Optional data model to be passed.",
            table: {
                category: "Schema",
            },
        },
        emailDocumentSchemaUI: {
            description:
                "Optional schema to be passed for providing custom form to email documents.",
            table: {
                category: "Schema",
            },
        },
        emailDataModel: {
            description: "Optional data model to be passed.",
            table: {
                category: "Schema",
            },
        },
        useRefresh: {
            description: "Refreshing the documents uploaded in the container.",
            table: {
                category: "Boolean"
            }
        },
        tableClass: {
            description: "Table Class",
            table: {
                category: "class",
            },
        },
        titleClass: {
            description: "Title Class",
            table: {
                category: "class",
            },
        },
        parentClass: {
            description: "Parent Class",
            table: {
                category: "class",
            },
        },
    },
};

const Template = (args) => <UploadDocumentFunctionalComp {...args} />;

export const Grouped = Template.bind({});
Grouped.args = functionalArgs;

export const NonGrouped = Template.bind({});
NonGrouped.args = {...functionalArgs, isExpandRow: false};
