export const emailConfigs = [
    {
        "NotificationKey": "FormalQuote",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "''",
        "Subject": "'Quote for ' & InsuredAccount.DisplayName & ' '  & QuoteNumber & '-' & QuoteVersion ",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/QuoteOfferTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "PolicyBound",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "'ysaran@cogitate.us'",
        "Subject": "'Policy Issued ' & InsuredAccount.DisplayName & ' '  & PolicyNumber ",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/PolicyBoundTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "BindEndorsement",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "TotalPremium.EffectivePremium != 0 ? 'npatidar@cogitate.us' : ''",
        "Subject": "'Endorsement for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/BindEndTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "EndorsementReferred",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "'npatidar@cogitate.us'",
        "Subject": "'Referred Endorsement for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/EndReferredTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "EndorsementReferredBnCError",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "'npatidar@cogitate.us'",
        "Subject": "'Referred Endorsement Error for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/EndReferredBnCErrorTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "EndorsementDeclined",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "''",
        "Subject": "'Declined Endorsement Request for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/EndDeclinedTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "ApproveReinstatement",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "''",
        "Subject": "'Declined Endorsement Request for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "JEB/templates/Personal/Homeowners/common/Notifications/EndDeclinedTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    },
    {
        "NotificationKey": "ApproveCancellation",
        "Lob": "XS",
        "From": "noreply@cogitate.us",
        "To": "Agent.Details.Contact.EmailId",
        "CC": "''",
        "BCC": "''",
        "Subject": "'Declined Endorsement Request for ' & InsuredAccount.DisplayName & ' '  & PolicyNumber",
        "BodyTemplate": "diep2/JEB/templates/Personal/Homeowners/common/Notifications/EndDeclinedTemplate.html",
        "NotificationType": "E",
        "HasAttachments": false,
        "PushToDMS": false,
        "DmsFolderName": "Correspondence"
    }
]