const dateKeys = {
    Seconds: "Seconds",
    Minutes: "Minutes",
    Hours: "Hours",
    Days: "Days",
    Weeks: "Weeks",
    Months: "Months",
    Years: "Years",
    DateFormatyyymmdd: "yyyy-mm-dd"
}

const commonKeys = {
    Code: "Code",
    Description: "Description",
    Value: "Value",
    Text: "Text",
    IsErrored: "IsErrored",
    Valid: "Valid",
    Errors: "Errors",
    EmptyString: "",
    DefaultTemplate: "Default Template",
    ModuleQuote: "Quote",
    ModuleApplication: "Application",
    ModuleEndorsement: "Endorsement",
    ModuleRenewal: "Renewal",
    ModuleCancel: "Cancel",
    ModuleReinstate: "Reinstate",
    RoleAgent: "Agent",
    Agency: "Agency",
    RoleUW: "UW",
    RoleUnderwriter: "Underwriter",
    RoleSrUnderwriter: "Sr. Underwriter",
    RoleUnderwritingManager: "Underwriting Manager",
    RoleAdmin: "Admin",
    RoleMGA: "MGA",
    RoleCarrier: "Carrier",
    RoleAuditor: "Auditor",
    RoleSUW: "SUW",
    ActionAllow: "Allow",
    ActionRefer: "Refer",
    ActionBlock: "Block",
    ActionInEligible: "InEligible",
    ActionEmailQuote: "EmailQuote",
    ActionEmailFormalQuote: "EmailFormalQuote",
    ActionPrintQuote: "PrintQuote",
    ActionDownloadRatesheet: "DownloadRatesheet",
    ActionSmsQuote: "SmsQuote",
    ActionEmailAndDownload: "ActionEmailAndDownload",
    NotificationTypeSMS: "S",
    NotificationTypeEmail: "E",
    NotificationFormatHTML: "html",
    NotificationFormatPDF: "pdf",
    NotificationFormatTEXT: "text",
    TemplateNameNotificationQuote: "toga/commercial/auto/common/ca_email.html",
    TemplateNameNotificationFormalQuote: "toga/commercial/auto/common/formalquote.html",
    TemplateNameNotificationFormalQuoteMessageBody: "toga/commercial/auto/common/formalquotemessagebody.html",
    TemplateNameCancelReinstate: "toga/commercial/auto/common/REI_CAN_document.html",
    TemplateGLRateSheet: "toga/templates/commercial/auto/common/ratesheets/Canopius General Liabilty Rater.html",
    TemplateALRateSheet: "toga/templates/commercial/auto/common/ratesheets/Alpine Liability Rater.html",
    TemplateMTGRateSheet: "toga/templates/commercial/auto/common/ratesheets/Canopius Motor Truck Cargo Rater.html",
    TemplatePDRateSheet: "toga/templates/commercial/auto/common/ratesheets/Canopius Phys Dam Rater.html",
    EmailFormalQuote: "toga/templates/commercial/auto/common/formalquote/formalquote.html",
    EmailPolicyBind: "toga/templates/commercial/auto/common/notifications/bindsuccessmailbody.html",
    EmailPolicyCancel: "toga/templates/commercial/auto/common/notifications/cancelsuccessmailbody.html",
    EmailPolicyReInstate: "toga/templates/commercial/auto/common/notifications/reinstatesuccessmailbody.html",
    TrueString: "true",
    FalseString: "false",
    PageChangeFormName: "pageChangeForm",
    New: "new",
    SubmitAndAddAnother: "submitAndAddAnother",
    SubmitOnly: "SubmitOnly",
    CloseModal: "closeModal",
    Completed: "completed",
    Errored: "errored",
    Deleted: "Deleted",
    DatatTableMode: "checkbox",
    AddNewDriver: "addnewDriver",
    Disabled: "disabled",
    Disable: "disable",
    Selected: "selected",
    Options: "options",
    FMCSA: "FMCSA",
    YesString: "Yes",
    NoString: "No",
    TemplateNameDeclineSubmission: "toga/templates/commercial/auto/common/notifications/submissiondecline.html",
    TemplateNameHoldSubmission: "toga/templates/commercial/auto/common/notifications/submissionhold.html",
    UnderwriterReferral: "UnderwriterReferral",
    String: 'string',
    TemplateNameFmcsaDocument: "diep2/templates/toga/templates/commercial/auto/common/fmcsa/businessinfo_bydotnumber.html",
    Individual: "Individual",
    LocationTypeArray: "array",
    Active: "Active"
}
const accountHubKeys = {
    AgencyName: "agentName",
    UWName: "underwriterName",
}

export {
    commonKeys,
    dateKeys,
    accountHubKeys
}