export const newPolicy = {
    "AccountId": "Agent",
    "QuoteNumber": "SDRHHO3OR230355",
    "IsInForce": true,
    "IsPolicyBind": true,
    "IsRenewed": false,
    "PolicyNumber": "SDRHHO3OR230355",
    "EffectiveDate": "2024-12-07",
    "ExpirationDate": "2024-12-23",
    "BindDate": "2023-12-23",
    "QuoteDate": "2023-12-23",
    "QuoteExpDate": "2024-01-22",
    "NoOfTimesRenewed": "0",
    "PolicyStatus": "Policy In Force",
    "PolicyStatusRemarks": "",
    "CurrentVersion": "1.0",
    "CurrentVersionEffectiveFrom": "",
    "RenewalTerm": 0,
    "RenewalQuoteID": 0,
    "IsOOS": false,
    "NonFunctional": {
        "LastSubmittedPage": "/Personal/HomeOwners/Application/Summary/Bind",
        "InsuredOTP": "",
        "Milestones": [
            0,
            1,
            2,
            3
        ]
    },
    "Underwriting": {
        "IsAnyBusinessOnPremise": "false",
        "AnyResidenceEmployees": "false",
        "NoOfPartTimeEmployees": "",
        "NoOfFullTimeEmployees": "",
        "IsPropertyInHazardArea": "false",
        "AnyOtherResidence": "false",
        "IsAnyOtherInsuranceWithCompany": "false",
        "ListPolicyNumber": "",
        "AnyCoverageHistoryInLastThreeYear": "false",
        "HadForeclosureRepossessionOrBankruptcy": "false",
        "ReasonForForeclosureRepossessionOrBankruptcy": "",
        "StatusForForeclosureRepossessionOrBankruptcy": "1",
        "DateClosedStatusForForeclosureRepossessionOrBankruptcy": "",
        "IsApplicantDelinquentOnMortgageOrTaxPayment": "false",
        "IsExoticAnimalOrPet": "false",
        "IsAnimalWithBiteHistory": "false",
        "AddTypeOfAnimalBox": "",
        "AnimalOrPetBreed": "",
        "IsLakeOrPondOrDockOnPremises": "false",
        "IsPropertyMoreThanFiveAcres": "false",
        "NoOfAcres": "",
        "DescribeLandUse": "",
        "OtherStructureOnPremise": "false",
        "DescribeStructureOnPremise": "",
        "IsBuildingRetrofittedForEarthQuake": "false",
        "IsAnyCriminalHistory": "false",
        "IsAnyExistingDamages": "false",
        "IsUnderRenovationOrReconstruction": "false",
        "ContractorName": "",
        "CompletionDate": "",
        "CompletedValue": "",
        "IsHouseForSale": "false",
        "IsAnyCommercialOrNonResidentialProperty": "false",
        "IsTrampolineOnPremise": "false",
        "IsStructureConverted": "false",
        "IsAnySwimingPool": "false",
        "IsSwimingPoolEnclosed": "false",
        "IsAnyDivingBoardsPresent": "false",
        "IsAnySlidesPresent": "false",
        "IsThePropertyCurrentlyInsured": "false",
        "PriorInsuranceCompany": "",
        "PriorInsurancePolicyNumber": "",
        "PriorInsuranceExpirationDate": ""
    },
    "Rules": {
        "Action": "Allow",
        "MatchingRules": []
    },
    "DiscountAndSurcharges": {
        "Description": ""
    },
    "Risks": {
        "Properties": [
            {
                "PropertyAge": 0,
                "UnitId": 1,
                "UnitNumber": "1",
                "Name": "",
                "UnitType": "P",
                "Status": "",
                "PropertyRiskAttributes": {
                    "IsLLC": "false",
                    "HasSameMailingAddress": "true",
                    "OccupancyType": "Primary",
                    "CoverageStartDate": "",
                    "YearBuilt": "2014",
                    "SquareFeet": "1667",
                    "ConstructionType": "Frame",
                    "ProtectionClass": "2",
                    "HydrantDistance": "456",
                    "FireStationDistance": "44",
                    "DistanceToTidalWater": "456",
                    "FireStationDriveDuration": "15",
                    "NoOfStories": "1",
                    "NoOfFamilies": "1",
                    "Foundation": "Open",
                    "FireScore": "low",
                    "FireAlarm": "None",
                    "BurglarAlarms": "None",
                    "SprinklerSystem": "Yes",
                    "ShortTermRental": "false",
                    "WeeksRentedPerYear": "",
                    "Deadbolt": "false",
                    "FireExtinguisher": "false",
                    "VisibleToNeighbours": "false",
                    "RoofType": "Tile",
                    "RoofUpdateType": "None",
                    "RoofUpdateYear": "2014",
                    "HeatingType": "None",
                    "HeatingUpdateType": "None",
                    "HeatingUpdateYear": "2014",
                    "ElectricalType": "Circuit Breakers",
                    "ElectricalUpdateType": "None",
                    "ElectricalUpdateYear": "2014",
                    "PlumbingType": "Galvanized",
                    "PlumbingUpdateType": "None",
                    "PlumbingUpdateYear": "2014",
                    "MinimumPremium": "",
                    "BrushFireDistance": "64656",
                    "DsValFireScore": "",
                    "DsValBrushFireDistance": "",
                    "CovBPercentageOfCovA": "10.00",
                    "CovCPercentageOfCovA": "50.00",
                    "CovDPercentageOfCovA": "20.00"
                },
                "Audit": {
                    "CreatedBy": "",
                    "CreatedOn": "",
                    "LastUpdatedBy": "",
                    "LastUpdatedOn": ""
                },
                "AdditionalParties": {
                    "MortgageeDetails": [],
                    "AdditionalInsured": [],
                    "AdditionalInterest": [],
                    "Trust": []
                },
                "Premium": {
                    "EffectivePremium": 3240,
                    "AnnualPremium": 3240,
                    "Surcharge": 0,
                    "Discount": -168.10500000000002,
                    "AnnualSurcharge": 0,
                    "AnnualDiscount": -168.10500000000002,
                    "FullyEarnedPremium": 0
                },
                "PremiumFactors": [
                    {
                        "Name": "",
                        "Status": "InActive",
                        "Type": "",
                        "Description": "",
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": null,
                        "LimitAmount": null,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "LiabPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Liability Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 100000,
                        "LimitAmount": 100000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "MedPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Medical Payment Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 1000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "LAPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Loss Assessment Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 1000,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "OLPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Ordinance and Law Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 10,
                        "LimitAmount": 10,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "ClaimRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Claim Loss Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "ConstructionRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Construction Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "FireAlarmRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Fire Alarm Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "BurglarAlarmRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Burglar Alarm Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "SprinklerRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Sprinkler Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": -2,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "YearBuiltRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Year Built Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "ERCRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Extended RC Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "OccRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Occupancy Rate Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "DedRate",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Deductible Rate Surcharge",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": -10,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "IncCovCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Increased Cov C Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "RCCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Replacement Cost Contents Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "PIPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Personal Injury Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "SCCPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Special Computer Coverage Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "SPPPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Special Personal Property Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "IDFraudPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Identity Fraud Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "MechBrPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Mechanical Breakdown Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "WaterBackupPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Water Backup Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "BRExtPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Builder Risk Extended Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "TOBMPrem",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Theft Of Building Material Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "Base Premium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Base Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 175,
                        "EffectivePremium": 175,
                        "PremiumDifference": 175,
                        "AnnualPremium": 175
                    },
                    {
                        "Name": "PCPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Protection Class Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 1,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "IncLimPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Increased Limit Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 8.004999999999999,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 1225.875,
                        "EffectivePremium": 1225.875,
                        "PremiumDifference": 1225.875,
                        "AnnualPremium": 1225.875
                    },
                    {
                        "Name": "SurchargePremium",
                        "Status": "Active",
                        "Type": "DIS",
                        "Description": "Surcharge Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0.88,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": -168.10500000000002,
                        "EffectivePremium": -168.10500000000002,
                        "PremiumDifference": -168.10500000000002,
                        "AnnualPremium": -168.10500000000002
                    },
                    {
                        "Name": "WFPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "WildFire Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 1,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    },
                    {
                        "Name": "MinPremium",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Minimum Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 1000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 2007.23,
                        "EffectivePremium": 2007.23,
                        "PremiumDifference": 2007.23,
                        "AnnualPremium": 2007.23
                    },
                    {
                        "Name": "RoundFactor",
                        "Status": "Active",
                        "Type": "",
                        "Description": "Round Factor Premium",
                        "IsApplicable": true,
                        "IsSelected": true,
                        "IsMandatory": false,
                        "Rate": 0,
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "Premium": 0,
                        "EffectivePremium": 0,
                        "PremiumDifference": 0,
                        "AnnualPremium": 0
                    }
                ],
                "Coverages": [
                    {
                        "Id": "1",
                        "Name": "coverageA",
                        "Description": "Coverage A - Dwelling",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "900000",
                        "Limit": 900000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "2",
                        "Name": "coverageB",
                        "Description": "Coverage B - Other Structures",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "90000",
                        "Limit": 90000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "3",
                        "Name": "coverageC",
                        "Description": "Coverage C - Personal Property",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "450000",
                        "Limit": 450000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "4",
                        "Name": "coverageD",
                        "Description": "Coverage D - Loss of Use",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "180000",
                        "Limit": 180000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "5",
                        "Name": "coverageE",
                        "Description": "Coverage E - Liability",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "100000",
                        "Limit": 100000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "6",
                        "Name": "coverageF",
                        "Description": "Coverage F - Medical Payments",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1000",
                        "Limit": 1000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "7",
                        "Name": "lossAssessment",
                        "Description": "Loss Assessment",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1000",
                        "Limit": 1000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "8",
                        "Name": "ordinanceOrLaw",
                        "Description": "Ordinance or Law",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "10",
                        "Limit": 10,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "9",
                        "Name": "increasedCovC",
                        "Description": "Increased Cov C Option",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "None",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "10",
                        "Name": "personalInjuryCover",
                        "Description": "Personal Injury Cover",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "11",
                        "Name": "specialComputerCoverage",
                        "Description": "Special Computer Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "12",
                        "Name": "replacmentCostContents",
                        "Description": "Replacement Cost Contents",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "13",
                        "Name": "specialPersonalPropertyCoverage",
                        "Description": "Special Personal Property Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "14",
                        "Name": "waterBackup",
                        "Description": "Water Back Up",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "0",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "15",
                        "Name": "extendedReplacementCost",
                        "Description": "Extended replacement cost",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "16",
                        "Name": "identityFraudExp",
                        "Description": "Identity fraud expense",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "17",
                        "Name": "buildersRiskExtentedCoverages",
                        "Description": "Builders Risk Extended Coverages",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "18",
                        "Name": "theftOfBuildingMaterialsCoverage",
                        "Description": "Theft of Building Materials Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "19",
                        "Name": "mechanicalBreakDownCoverage",
                        "Description": "Mechanical Breakdown Coverage",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "no",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "20",
                        "Name": "allOtherPerils",
                        "Description": "All Other Perils Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "2500",
                        "Limit": 2500,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "21",
                        "Name": "smokeDeductible",
                        "Description": "Smoke Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "22",
                        "Name": "theftDeductible",
                        "Description": "Theft Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "23",
                        "Name": "waterDeductible",
                        "Description": "Water Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "24",
                        "Name": "windDeductible",
                        "Description": "Wind Deductible",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "Excluded",
                        "Limit": 0,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    },
                    {
                        "Id": "25",
                        "Name": "TIV",
                        "Description": "Total Insurable Value",
                        "Type": "",
                        "SettlementType": "",
                        "Value": "1620000",
                        "Limit": 1620000,
                        "LimitAmount": 0,
                        "Deductible": 0,
                        "IsApplicable": false,
                        "IsSelected": false,
                        "IsMandatory": false,
                        "Status": ""
                    }
                ],
                "Address": {
                    "IsManual": true,
                    "StreetName": "",
                    "AddressLine1": "400 Bizzell Street",
                    "AddressLine2": "",
                    "City": "College Station",
                    "State": "OR",
                    "County": "",
                    "CountyCode": "",
                    "Zip": "77843",
                    "Country": "",
                    "CountryCode": "",
                    "PlaceId": "",
                    "Number": 0,
                    "Name": "",
                    "Long": "",
                    "Lat": "",
                    "Description": "",
                    "AddressType": "P",
                    "FormattedAddress": "",
                    "UnFormattedAddress": "400 Bizzell Street, College Station, OR, 77843",
                    "Status": "",
                    "AptSuite": "",
                    "PoBox": "",
                    "CityCode": "",
                    "Territory": "",
                    "TerritoryCode": ""
                }
            }
        ]
    },
    "FeesAndTaxes": [
        {
            "Code": "PRTX",
            "Description": "Premium Tax",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 0.02,
            "ValueType": "P",
            "Amount": 68.8,
            "AnnualAmount": 68.8,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "FMTX",
            "Description": "Fire Marshall Tax",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 0.003,
            "ValueType": "P",
            "Amount": 10.32,
            "AnnualAmount": 10.32,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "PFEE",
            "Description": "Policy Fee",
            "Type": "Fee",
            "IsOverride": false,
            "Status": "Active",
            "Value": 100,
            "ValueType": "V",
            "Amount": 100,
            "AnnualAmount": 100,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "INSFEE",
            "Description": "Inspection Fee",
            "Type": "Fee",
            "IsOverride": false,
            "Status": "Active",
            "Value": 100,
            "ValueType": "V",
            "Amount": 100,
            "AnnualAmount": 100,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "STF",
            "Description": "Stamping Fee",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 10,
            "ValueType": "V",
            "Amount": 10,
            "AnnualAmount": 10,
            "ProductFeesAndTaxes": null
        }
    ],
    "TransactionFeesAndTaxes": [
        {
            "Code": "PRTX",
            "Description": "Premium Tax",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 0.02,
            "ValueType": "P",
            "Amount": 68.8,
            "AnnualAmount": 68.8,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "FMTX",
            "Description": "Fire Marshall Tax",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 0.003,
            "ValueType": "P",
            "Amount": 10.32,
            "AnnualAmount": 10.32,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "PFEE",
            "Description": "Policy Fee",
            "Type": "Fee",
            "IsOverride": false,
            "Status": "Active",
            "Value": 100,
            "ValueType": "V",
            "Amount": 100,
            "AnnualAmount": 100,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "INSFEE",
            "Description": "Inspection Fee",
            "Type": "Fee",
            "IsOverride": false,
            "Status": "Active",
            "Value": 100,
            "ValueType": "V",
            "Amount": 100,
            "AnnualAmount": 100,
            "ProductFeesAndTaxes": null
        },
        {
            "Code": "STF",
            "Description": "Stamping Fee",
            "Type": "Tax",
            "IsOverride": false,
            "Status": "Active",
            "Value": 10,
            "ValueType": "V",
            "Amount": 10,
            "AnnualAmount": 10,
            "ProductFeesAndTaxes": null
        }
    ],
    "TransactionTotalPremium": {
        "BasicPremium": 3240,
        "Surcharge": 0,
        "Discount": 0,
        "MinPremium": 1000,
        "EffectivePremium": 3240,
        "AnnualPremium": 3240,
        "PriorAnnualPremium": 0,
        "EffectivePremiumWithFeesAndTaxes": null,
        "AnnualPremiumWithFeesAndTaxes": null,
        "AnnualFees": null,
        "AnnualTax": null,
        "Taxes": null,
        "Fees": null,
        "CommutativeEffectivePremium": 3240,
        "MonthlyEffectivePremium": 270,
        "WorkingMonthlyPremium": 270
    },
    "TotalPremium": {
        "BasicPremium": 3240,
        "Surcharge": 0,
        "Discount": 0,
        "MinPremium": 1000,
        "EffectivePremium": 3240,
        "AnnualPremium": 3240,
        "PriorAnnualPremium": 0,
        "CommutativeEffectivePremium": 3240,
        "MonthlyEffectivePremium": 270,
        "FullyEarnedPremium": 0,
        "WorkingMonthlyPremium": 270,
        "Fees": 200,
        "Taxes": 89.12,
        "AnnualFees": 200,
        "AnnualTax": 89.12,
        "EffectivePremiumWithFeesAndTaxes": 3529.12,
        "AnnualPremiumWithFeesAndTaxes": 3529.12
    },
    "Premium": {
        "EffectivePremium": 0,
        "AnnualPremium": 0,
        "Surcharge": 0,
        "Discount": 0,
        "AnnualSurcharge": 0,
        "AnnualDiscount": 0,
        "FullyEarnedPremium": 0
    },
    "PremiumFactors": [
        {
            "Name": "RiskPrem",
            "Type": "",
            "Description": "Risk Premium",
            "Rate": 0,
            "Limit": 0,
            "LimitAmount": 0,
            "Premium": 0,
            "AnnualPremium": 0,
            "Status": "Active",
            "IsApplicable": true,
            "IsSelected": true,
            "IsMandatory": false,
            "Deductible": 0,
            "EffectivePremium": 0,
            "PremiumDifference": 0
        }
    ],
    "PolicyCoverages": {
        "Coverages": [
            {
                "Id": "1",
                "Name": "Adjust Premium",
                "Description": "Adjust Premium",
                "Type": "",
                "SettlementType": "",
                "Value": "",
                "Limit": 0,
                "LimitAmount": 0,
                "Deductible": 0,
                "IsApplicable": false,
                "IsSelected": false,
                "IsMandatory": false,
                "Status": ""
            },
            {
                "Id": "2",
                "Name": "PTIV",
                "Description": "PTIV",
                "Type": "",
                "SettlementType": "",
                "Value": "1620000",
                "Limit": 1620000,
                "LimitAmount": 0,
                "Deductible": 0,
                "IsApplicable": false,
                "IsSelected": false,
                "IsMandatory": false,
                "Status": ""
            }
        ]
    },
    "Forms": [
        {
            "Status": "",
            "FormName": "UTS-COVPG (03-21)",
            "FormDesc": "Cover Page",
            "Sequence": 1,
            "FormType": "Static",
            "Template": "ji5ksayq3la",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO029",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HOS-D-2 (01-21)",
            "FormDesc": "Homeowner Declarations",
            "Sequence": 2,
            "FormType": "DynamicDocx",
            "Template": "jka3xoinf5w",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO002",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-SP-2 (12-95)",
            "FormDesc": "Forms & Endorsement Schedule",
            "Sequence": 3,
            "FormType": "DynamicDocx",
            "Template": "gybawn5righ",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO003",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HO-14s (12-95)",
            "FormDesc": "Business Pursuits Exclusion Home Day Care",
            "Sequence": 4,
            "FormType": "DynamicDocx",
            "Template": "txjnluslxez",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO004",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "DPS-5 (01-06)",
            "FormDesc": "Lead Contamination Exclusion",
            "Sequence": 5,
            "FormType": "DynamicDocx",
            "Template": "ptuwjpnpobr",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO005",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-74g (08-95)",
            "FormDesc": "Punitive Damages Exclusion",
            "Sequence": 6,
            "FormType": "DynamicDocx",
            "Template": "ibovighm0g0",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO006",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-419g (11-11)",
            "FormDesc": "Minimum Earned Premium",
            "Sequence": 7,
            "FormType": "DynamicDocx",
            "Template": "0ibmsoi20ba",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO008",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-326s (02-21)",
            "FormDesc": "Liberalization Clause Exclusion",
            "Sequence": 8,
            "FormType": "DynamicDocx",
            "Template": "llryvim0uvs",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO009",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-9g (06-22)",
            "FormDesc": "Service of Suit",
            "Sequence": 9,
            "FormType": "DynamicDocx",
            "Template": "qwrikvjhxgy",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO010",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-292g (08-22)",
            "FormDesc": "Mold Exclusion",
            "Sequence": 10,
            "FormType": "DynamicDocx",
            "Template": "aadkmpyp2hx",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO011",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HOS-86s (02-21)",
            "FormDesc": "EIFS Exclusion",
            "Sequence": 11,
            "FormType": "DynamicDocx",
            "Template": "pc25yjhvifb",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO012",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "NOTX0651 CW (01-23)",
            "FormDesc": "Privacy Notice",
            "Sequence": 12,
            "FormType": "Static",
            "Template": "n2oseuqda4b",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO013",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "NOTX0105CW (02-19)",
            "FormDesc": "Privacy Statement",
            "Sequence": 13,
            "FormType": "Static",
            "Template": "nvc1ue2ywza",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO014",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "NOTX0178CW (03-16)",
            "FormDesc": "Claims Reporting Information",
            "Sequence": 14,
            "FormType": "Static",
            "Template": "oi0lqxnnj1s",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO015",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-490 (11-18)",
            "FormDesc": "Total or Constructive Loss Clause",
            "Sequence": 15,
            "FormType": "DynamicDocx",
            "Template": "idaneiusfzs",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO017",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "NOTX0135CW (06-09)",
            "FormDesc": "Flood Damage Notice",
            "Sequence": 16,
            "FormType": "Static",
            "Template": "nszovc4iyyl",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO020",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-330S (04-16)",
            "FormDesc": "Existing Damage Exclusion",
            "Sequence": 17,
            "FormType": "DynamicDocx",
            "Template": "kmibhv2bh1u",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO021",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-601 (02-22)",
            "FormDesc": "Watercraft Exclusion",
            "Sequence": 18,
            "FormType": "DynamicDocx",
            "Template": "umn5ew3cdvo",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO023",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-607 (04-22)",
            "FormDesc": "Time Limit of Filing A Claim",
            "Sequence": 19,
            "FormType": "DynamicDocx",
            "Template": "dxddp2cp3xu",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO024",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-465 (10-16)",
            "FormDesc": "Demolition Exclusion",
            "Sequence": 21,
            "FormType": "DynamicDocx",
            "Template": "xi0f1guopcv",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO069",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-477 (07-19)",
            "FormDesc": "Marijuana-Cannabis Exclusion",
            "Sequence": 22,
            "FormType": "DynamicDocx",
            "Template": "3jqfpng0qqp",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO080",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-57g (01-93)",
            "FormDesc": "Measure of Recovery Endorsement",
            "Sequence": 23,
            "FormType": "DynamicDocx",
            "Template": "0ryenpq4nwt",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO081",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HO 00 03 (05-11)",
            "FormDesc": "HO3 Property Form",
            "Sequence": 24,
            "FormType": "Static",
            "Template": "z0ct4ncj0yh",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO092",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HO 01 36 (01-22)",
            "FormDesc": "Special Provisions Oregon",
            "Sequence": 25,
            "FormType": "Static",
            "Template": "phjri0qfwtk",
            "IsMandatory": true,
            "IsChecked": true,
            "AcordCode": "HO093",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-137g (02-18)",
            "FormDesc": "Assault & Battery Exclusion",
            "Sequence": 26,
            "FormType": "DynamicDocx",
            "Template": "nwndce4icl5",
            "IsMandatory": false,
            "IsChecked": true,
            "AcordCode": "HO007",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-39s (04-11)",
            "FormDesc": "Pollution Exclusion",
            "Sequence": 27,
            "FormType": "DynamicDocx",
            "Template": "tfswnfwxw2f",
            "IsMandatory": false,
            "IsChecked": true,
            "AcordCode": "HO016",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "UTS-32g (11-15)",
            "FormDesc": "Occupancy Clause",
            "Sequence": 28,
            "FormType": "DynamicDocx",
            "Template": "c24h3g541ry",
            "IsMandatory": false,
            "IsChecked": true,
            "AcordCode": "HO019",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HO 04 35 (05-11)",
            "FormDesc": "Increased Loss Assessment",
            "Sequence": 52,
            "FormType": "DynamicDocx",
            "Template": "ypy2tjemo0p",
            "IsMandatory": false,
            "IsChecked": true,
            "AcordCode": "HO095",
            "File": "",
            "Dmspath": ""
        },
        {
            "Status": "",
            "FormName": "HO 04 77 (10-00)",
            "FormDesc": "Increased Ordinance & Law",
            "Sequence": 55,
            "FormType": "DynamicDocx",
            "Template": "s4qxv0iuc50",
            "IsMandatory": false,
            "IsChecked": true,
            "AcordCode": "HO098",
            "File": "",
            "Dmspath": ""
        }
    ],
    "Claims": [],
    "ExternalRefrences": [
        {
            "Id": "",
            "ReferenceNumber": "",
            "ReferenceTarget": "",
            "Status": ""
        }
    ],
    "Audit": {
        "CreatedBy": "agent.rothert",
        "CreatedOn": "2023-12-23T06:33:34.489Z",
        "LastUpdatedBy": "agent.rothert",
        "LastUpdatedOn": "2023-12-23T06:34:21.239Z"
    },
    "JointPolicyHolders": [
        {
            "Id": "1",
            "FirstName": "",
            "MiddleName": "",
            "LastName": "",
            "DateOfBirth": "",
            "InsuredType": "",
            "Occupation": "",
            "IsHighProfile": false,
            "IsAddressSameAsRisk": null,
            "OtherDetails": {
                "DateOfBirth": "",
                "Occupation": "",
                "EmployerName": "",
                "EmployerAddress": {
                    "IsManual": false,
                    "StreetName": "",
                    "AddressLine1": "",
                    "AddressLine2": "",
                    "City": "",
                    "State": "",
                    "County": "",
                    "CountyCode": "",
                    "Zip": "",
                    "Country": "",
                    "CountryCode": "",
                    "PlaceId": "",
                    "Number": 0,
                    "Name": "",
                    "Long": "",
                    "Lat": "",
                    "Description": "",
                    "AddressType": "M",
                    "FormattedAddress": "",
                    "UnFormattedAddress": "",
                    "Status": "",
                    "AptSuite": "",
                    "PoBox": "",
                    "CityCode": "",
                    "Territory": "",
                    "TerritoryCode": ""
                }
            },
            "Communications": [
                {
                    "Type": "PhNo",
                    "SubType": "Primary",
                    "Value": "",
                    "Status": ""
                },
                {
                    "Type": "Email",
                    "SubType": "Primary",
                    "Value": "",
                    "Status": ""
                }
            ],
            "Address": {
                "IsManual": false,
                "StreetName": "",
                "AddressLine1": "",
                "AddressLine2": "",
                "City": "",
                "State": "",
                "County": "",
                "CountyCode": "",
                "Zip": "",
                "Country": "",
                "CountryCode": "",
                "PlaceId": "",
                "Number": 0,
                "Name": "",
                "Long": "",
                "Lat": "",
                "Description": "",
                "AddressType": "M",
                "FormattedAddress": "",
                "UnFormattedAddress": "",
                "Status": "",
                "AptSuite": "",
                "PoBox": "",
                "CityCode": "",
                "Territory": "",
                "TerritoryCode": ""
            },
            "Age": {
                "Value": 0,
                "ValueType": ""
            }
        }
    ],
    "InsuredAccount": {
        "Type": "",
        "CreationDate": "",
        "UserName": "",
        "FirstName": "Test Ashwith",
        "MiddleName": "",
        "LastName": "Test Ashwith",
        "DisplayName": "Test Ashwith Test Ashwith",
        "HasJointPolicyHolder": "false",
        "OtherDetails": {
            "DateOfBirth": "2005-12-07",
            "Occupation": "Business",
            "ApplicantEmployerName": "Testing",
            "ApplicantEmployerAddress": {
                "IsManual": false,
                "StreetName": "",
                "AddressLine1": "",
                "AddressLine2": "",
                "City": "",
                "State": "",
                "County": "",
                "CountyCode": "",
                "Zip": "",
                "Country": "",
                "CountryCode": "",
                "PlaceId": "",
                "Number": 0,
                "Name": "",
                "Long": "",
                "Lat": "",
                "Description": "",
                "AddressType": "M",
                "FormattedAddress": "",
                "UnFormattedAddress": "",
                "Status": "",
                "AptSuite": "",
                "PoBox": "",
                "CityCode": "",
                "Territory": "",
                "TerritoryCode": ""
            }
        },
        "BusinessInfo": {
            "BusinessType": "",
            "YearsInBusiness": 0,
            "IncorporationAge": "",
            "BusinessName": "",
            "DisplayName": "",
            "RegistrationNumber": "",
            "BusinessStruct": "",
            "SpecialRisk": "",
            "NoOfOwners": 0,
            "FullTimeEmployees": 0,
            "PartTimeEmployees": 0,
            "Website": "",
            "IndustryType": "",
            "BusinessDecsription": "",
            "AnnualRevenue": 0,
            "NumberOFLocations": 0,
            "Locations": [
                {
                    "NickName": "",
                    "LocationNumber": 0,
                    "IsValid": false,
                    "Status": "",
                    "Type": "M",
                    "Address": {
                        "IsManual": true,
                        "StreetName": "",
                        "AddressLine1": "400 Bizzell Street",
                        "AddressLine2": "",
                        "City": "College Station",
                        "State": "OR",
                        "County": "",
                        "CountyCode": "",
                        "Zip": "77843",
                        "Country": "",
                        "CountryCode": "",
                        "PlaceId": "",
                        "Number": 0,
                        "Name": "",
                        "Long": "",
                        "Lat": "",
                        "Description": "",
                        "AddressType": "M",
                        "FormattedAddress": "",
                        "UnFormattedAddress": "400 Bizzell Street, College Station, OR, 77843",
                        "Status": "",
                        "AptSuite": "",
                        "PoBox": "",
                        "CityCode": "",
                        "Territory": "",
                        "TerritoryCode": ""
                    }
                }
            ]
        },
        "Communications": [
            {
                "Type": "PhNo",
                "SubType": "Primary",
                "Value": "9356287777",
                "Status": ""
            },
            {
                "Type": "Email",
                "SubType": "Primary",
                "Value": "abhatt@cogitate.us",
                "Status": ""
            }
        ],
        "BankDetails": {
            "AccountName": "",
            "BankName": "",
            "BranchName": "",
            "AccountType": "",
            "RoutingNo": ""
        }
    },
    "AgentCommission": {
        "Value": "",
        "ValueType": ""
    },
    "Transaction": {
        "Date": "2023-12-23",
        "EffectiveDate": "2024-12-07",
        "Type": "Policy",
        "Status": "Committed",
        "Number": 0,
        "IsOutOfSequence": false,
        "RequestedBy": "",
        "RequestedById": "",
        "PremiumType": "",
        "PolicyVersion": "",
        "FileType": "",
        "FileName": "",
        "File": "",
        "Remarks": "",
        "ReasonId": null,
        "MEP": 0.25,
        "Reason": "",
        "RenewalOffers": {
            "RenewalOfferId": "",
            "CurrentPremium": 0,
            "RenewalPremium": 0,
            "IsUpdateRenewalPremium": false,
            "RenewalOfferFlags": {
                "CreatedOn": "",
                "UpdatedOn": "",
                "CreatedBy": "",
                "UpdatedBy": "",
                "EmailSentFlag": false
            }
        },
        "TransactionStatusHistory": {
            "OldStatus": "",
            "NewStatus": "",
            "ChangedBy": "",
            "ChangedDate": ""
        },
        "Verification": {
            "IsInsuredESignVerified": false,
            "IsAgentESignVerified": false,
            "IsEmailVerified": false,
            "IsOTPVerified": false,
            "InsuredOTP": ""
        }
    },
    "PolicyStatusHistory": [
        {
            "Id": null,
            "OldStatus": "",
            "NewStatus": "Quote Indication",
            "Remarks": "",
            "ChangedBy": "Paul Rothert",
            "ChangedDate": "2023-12-23T06:32:44.721Z"
        },
        {
            "Id": null,
            "OldStatus": "Quote Indication",
            "NewStatus": "Submission",
            "Remarks": "",
            "ChangedBy": "Paul Rothert",
            "ChangedDate": "2023-12-23T06:33:02.686Z"
        },
        {
            "Id": null,
            "OldStatus": "Submission",
            "NewStatus": "Quote Offered",
            "Remarks": "",
            "ChangedBy": "Paul Rothert",
            "ChangedDate": "2023-12-23T06:33:40.595Z"
        },
        {
            "Id": null,
            "OldStatus": "Quote Offered",
            "NewStatus": "Bind Request - Awaiting UW Approval",
            "Remarks": "",
            "ChangedBy": "Paul Rothert",
            "ChangedDate": "2023-12-23T06:33:47.397Z"
        },
        {
            "OldStatus": "Policy In Force",
            "NewStatus": "Policy In Force",
            "Remarks": "",
            "ChangedBy": "Mark Rothert",
            "ChangedDate": "2023-12-23T06:34:21.236Z"
        }
    ],
    "Attributes": {
        "Client": "ROTHERT",
        "AppSource": "",
        "Carrier": "SD",
        "Coverholder": "RH",
        "Lob": "HO3",
        "State": "OR",
        "Product": "SDRHHO3OR",
        "RaterVersion": "1.0.0.0",
        "IsMasterPolicy": true,
        "MasterReferenceNumber": "",
        "IsTestPolicy": false,
        "Subjectivity": "",
        "UISchemaVersion": "v1",
        "AgentEffectiveDate": "2023-12-23",
        "QuoteValidity": {
            "Value": 0,
            "ValueType": ""
        },
        "RenewalConfigurations": {
            "AfterForUnderwriter": {
                "Value": 0,
                "ValueType": ""
            },
            "BeforeForUnderwriter": {
                "Value": 0,
                "ValueType": ""
            },
            "AfterForAgent": {
                "Value": 0,
                "ValueType": ""
            },
            "BeforeForAgent": {
                "Value": 0,
                "ValueType": ""
            }
        },
        "NoOfClaims": "0",
        "IsCoverageSaved": true,
        "AdjustPremiumType": "$",
        "AdjustPremiumReason": "",
        "AdjustPremiumOtherReason": "",
        "CanAgentApproveEnd": false
    },
    "TransactionHistory": [
        {
            "Type": "Policy",
            "Date": "2023-12-23",
            "EffectiveDate": "2024-12-07",
            "Number": 0,
            "Remarks": "",
            "EffectivePremium": 3240,
            "AnnualPremium": 3240,
            "EffectivePremiumWithFeesAndTaxes": 3529.12,
            "AnnualPremiumWithFeesAndTaxes": 3529.12,
            "UpdatedBy": "agent.rothert",
            "UpdatedOn": "2023-12-23T06:33:40.595Z"
        }
    ],
    "UnderWriter": {
        "Client": "ROTHERT",
        "Code": "13689",
        "Name": "Mark Rothert",
        "Status": "Active",
        "Address": {
            "IsManual": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "AddressLine1": null,
            "AddressLine2": null,
            "City": "Portland",
            "State": "OR",
            "County": "Multnomah County",
            "CountyCode": null,
            "Zip": "97213",
            "Country": "US",
            "CountryCode": "US",
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Lat": null,
            "Description": null,
            "AddressType": "M",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "AptSuite": null,
            "PoBox": null,
            "CityCode": null,
            "Territory": null,
            "TerritoryCode": null
        },
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "aghorpade@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "aghorpade@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "aghorpade@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "aghorpade@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "sdodmani@cogitate.us"
            }
        },
        "UWAttributes": null,
        "Reference": [
            "101001"
        ],
        "Products": [
            "SDRHHO3OR"
        ]
    },
    "Agent": {
        "Client": "ROTHERT",
        "Code": "13690",
        "Name": "OR Agent Paul",
        "Status": "Active",
        "Address": {
            "IsManual": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "AddressLine1": null,
            "AddressLine2": null,
            "City": "Portland",
            "State": "OR",
            "County": "Multnomah County",
            "CountyCode": null,
            "Zip": "97213",
            "Country": "US",
            "CountryCode": "US",
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Lat": null,
            "Description": null,
            "AddressType": "M",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "AptSuite": null,
            "PoBox": null,
            "CityCode": null,
            "Territory": null,
            "TerritoryCode": null
        },
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "abhatt@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "anair@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "anair@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "abhatt@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "sdodmani@cogitate.us"
            }
        },
        "Reference": [
            "101001"
        ],
        "Products": [
            "SDRHHO3OR"
        ]
    },
    "Agency": {
        "Client": "ROTHERT",
        "Code": "101001",
        "Name": "OR Test Agency",
        "Status": "Active",
        "Address": {
            "IsManual": null,
            "StreetName": "5234 NE Sandy Blvd.",
            "AddressLine1": null,
            "AddressLine2": null,
            "City": "Portland",
            "State": "OR",
            "County": "Multnomah County",
            "CountyCode": null,
            "Zip": "97213",
            "Country": "US",
            "CountryCode": "US",
            "PlaceId": null,
            "Number": null,
            "Name": null,
            "Long": null,
            "Lat": null,
            "Description": null,
            "AddressType": "M",
            "FormattedAddress": null,
            "UnFormattedAddress": "5234 NE Sandy Blvd., Portland, OR 97213",
            "Status": null,
            "AptSuite": null,
            "PoBox": null,
            "CityCode": null,
            "Territory": null,
            "TerritoryCode": null
        },
        "Details": {
            "Contact": {
                "HomePhone": "(503) 252-5454",
                "BusinessPhone": "(503) 252-5454",
                "Fax": "(503) 252-4048",
                "MobilePhone": "(503) 252-5454",
                "SendSms": false,
                "EmailId": "ksharma@cogitate.us",
                "SendQuoteEmail": false,
                "QuoteEmailId": "ksharma@cogitate.us",
                "SendPolicyEmail": false,
                "PolicyEmailId": "ksharma@cogitate.us",
                "FromEmailId": "noreply@cogitate.us",
                "EmailCCId": "ksharma@cogitate.us",
                "PreferedContactType": "E",
                "SecondaryEmailId": "ksharma@cogitate.us"
            }
        },
        "Reference": [
            "13689"
        ],
        "Products": [
            "SDRHHO3OR"
        ]
    },
    "PriorInsurances": {
        "IsCurrentlyInsured": false,
        "CompanyName": "",
        "OtherCompanyName": "",
        "EffectiveDate": "",
        "ExpirationDate": "",
        "Premium": 0,
        "Status": "",
        "LapsesInCoverages": "0",
        "ReasonLapsesInCoverages": ""
    },
    "PolicyTerm": {
        "Value": 12,
        "ValueType": "Months"
    },
    "PreviousPolicies": {
        "IsPreviousPolicy": "",
        "PreviousPolicyNumber": "",
        "OtherCoverages": "",
        "IsPreviousClaims": "",
        "NoOfClaims": "",
        "TotalAmountClaimed": ""
    },
    "RatingErrors": [],
    "PolicyLog": [],
    "DisplayRules": []
}