import gql from "graphql-tag";

export const CORE_POLICY_FIELDS = gql`
fragment CorePolicyFields on Policy {
  id
  AccountId
  QuoteNumber
  IsInForce
  IsPolicyBind
  IsRenewed
  PolicyNumber
  PolicyTerm {
    Value
    ValueType
  }
  IsOOS
  EffectiveDate
  ExpirationDate
  BindDate
  QuoteDate
  PolicyStatus
  PolicyStatusRemarks
  CurrentVersion
  CurrentVersionEffectiveFrom
  NoOfTimesRenewed
  QuoteExpDate
  RenewalTerm
  RenewalQuoteID
  Agency {
    Client
    Code
    Name
    Status
    Products
    Reference
    Details {
      Contact {
        HomePhone
        BusinessPhone
        Fax
        MobilePhone
        SendSms
        EmailId
        SendQuoteEmail
        QuoteEmailId
        SendPolicyEmail
        PolicyEmailId
        FromEmailId
        EmailCCId
        PreferedContactType
        SecondaryEmailId
      }
    }
    Address {
      IsManual
      StreetName
      AddressLine1
      AddressLine2
      City
      State
      County
      CountyCode
      Zip
      Country
      CountryCode
      PlaceId
      Number
      Name
      Long
      Lat
      Description
      AddressType
      FormattedAddress
      UnFormattedAddress
      Status
      AptSuite
      PoBox
      CityCode
      Territory
      TerritoryCode
    }
  }
  Agent {
    Client
    Code
    Name
    Status
    Products
    Reference
    Details {
      Contact {
        HomePhone
        BusinessPhone
        Fax
        MobilePhone
        SendSms
        EmailId
        SendQuoteEmail
        QuoteEmailId
        SendPolicyEmail
        PolicyEmailId
        FromEmailId
        EmailCCId
        PreferedContactType
        SecondaryEmailId
      }
    }
    Address {
      IsManual
      StreetName
      AddressLine1
      AddressLine2
      City
      State
      County
      CountyCode
      Zip
      Country
      CountryCode
      PlaceId
      Number
      Name
      Long
      Lat
      Description
      AddressType
      FormattedAddress
      UnFormattedAddress
      Status
      AptSuite
      PoBox
      CityCode
      Territory
      TerritoryCode
    }
  }
  UnderWriter {
    Client
    Code
    Name
    Status
    Products
    Reference
    Details {
      Contact {
        HomePhone
        BusinessPhone
        Fax
        MobilePhone
        SendSms
        EmailId
        SendQuoteEmail
        QuoteEmailId
        SendPolicyEmail
        PolicyEmailId
        FromEmailId
        EmailCCId
        PreferedContactType
        SecondaryEmailId
      }
    }
    Address {
      IsManual
      StreetName
      AddressLine1
      AddressLine2
      City
      State
      County
      CountyCode
      Zip
      Country
      CountryCode
      PlaceId
      Number
      Name
      Long
      Lat
      Description
      AddressType
      FormattedAddress
      UnFormattedAddress
      Status
      AptSuite
      PoBox
      CityCode
      Territory
      TerritoryCode
    }
    UWAttributes {
      UWOffice
      ContractNumber
      AccountExecCode
    }
  }
  NonFunctional {
    LastSubmittedPage
    Milestones
    InsuredOTP
  }
  PolicyStatusHistory{
    Id
    OldStatus
    NewStatus
    Remarks
    ChangedBy
    ChangedDate
  }
  Underwriting {
    IsAnyBusinessOnPremise
    AnyResidenceEmployees
    NoOfPartTimeEmployees
    NoOfFullTimeEmployees
    IsPropertyInHazardArea
    AnyOtherResidence
    IsAnyOtherInsuranceWithCompany
    ListPolicyNumber
    AnyCoverageHistoryInLastThreeYear  
    HadForeclosureRepossessionOrBankruptcy
    ReasonForForeclosureRepossessionOrBankruptcy
    StatusForForeclosureRepossessionOrBankruptcy
    DateClosedStatusForForeclosureRepossessionOrBankruptcy
    IsApplicantDelinquentOnMortgageOrTaxPayment
    IsExoticAnimalOrPet
    IsAnimalWithBiteHistory
    AddTypeOfAnimalBox
    AnimalOrPetBreed
    IsLakeOrPondOrDockOnPremises
    IsPropertyMoreThanFiveAcres
    NoOfAcres
    DescribeLandUse
    OtherStructureOnPremise
    DescribeStructureOnPremise
    IsBuildingRetrofittedForEarthQuake
    IsAnyCriminalHistory
    IsAnyExistingDamages
    IsUnderRenovationOrReconstruction
    ContractorName
    CompletionDate
    CompletedValue
    IsHouseForSale
    IsAnyCommercialOrNonResidentialProperty
    IsTrampolineOnPremise
    IsStructureConverted
    IsAnySwimingPool
    IsSwimingPoolEnclosed
    IsAnyDivingBoardsPresent
    IsAnySlidesPresent
    IsThePropertyCurrentlyInsured
    PriorInsuranceCompany
    PriorInsurancePolicyNumber
    PriorInsuranceExpirationDate
  }
  Transaction {
      Number
      Date
      EffectiveDate
      Type
      Status
      RequestedBy
      RequestedById
      PremiumType
      PolicyVersion 
      FileType
      FileName
      File
      IsOutOfSequence
      Remarks
      Reason
      MEP
      Verification{
        IsInsuredESignVerified
        IsAgentESignVerified
        IsEmailVerified
        IsOTPVerified
        InsuredOTP
      }
      TransactionStatusHistory {
        OldStatus
        NewStatus
        ChangedBy
        ChangedDate
      }
      RenewalOffers {
        RenewalOfferId
        CurrentPremium
        RenewalPremium
        IsUpdateRenewalPremium
        RenewalOfferFlags {
            CreatedOn
            UpdatedOn
            CreatedBy
            UpdatedBy
            EmailSentFlag
        }
      }
  }
  Premium {
    BasicPremium
    Surcharge
    Discount
    MinPremium
    AnnualPremium
    EffectivePremium
    AnnualPremiumWithFeesAndTaxes
    EffectivePremiumWithFeesAndTaxes
  }
  PremiumFactors {
    Name
    Status
    Type
    Description
    IsApplicable
    IsSelected
    IsMandatory
    Rate      
    Limit
    LimitAmount
    Deductible
    Premium
    EffectivePremium
    ProrateOn
    PremiumDifference
    Factor {
      Name
      Type
      Description
      Rate    
      Limit
      LimitAmount
      Premium
      Status
      IsApplicable
      IsSelected
      IsMandatory
      Deductible
      EffectivePremium
    }
  }
  TotalPremium {
    BasicPremium
    Surcharge
    Discount
    MinPremium
    EffectivePremium
    AnnualPremium
    PriorAnnualPremium
    EffectivePremiumWithFeesAndTaxes
    AnnualPremiumWithFeesAndTaxes
    AnnualFees
    AnnualTax
	  Taxes
	  Fees
    CommutativeEffectivePremium
    MonthlyEffectivePremium
    WorkingMonthlyPremium
  }
  TransactionTotalPremium {
    BasicPremium
    Surcharge
    Discount
    MinPremium
    EffectivePremium
    AnnualPremium
    PriorAnnualPremium
    EffectivePremiumWithFeesAndTaxes
    AnnualPremiumWithFeesAndTaxes
    AnnualFees
    AnnualTax
	  Taxes
	  Fees
    CommutativeEffectivePremium
    MonthlyEffectivePremium
    WorkingMonthlyPremium
  }
  PolicyCoverages {
    Coverages {
      Id
      Name
      Description
      Type
      SettlementType
      Value
      Limit
      LimitAmount
      Deductible
      IsApplicable
      IsSelected
      IsMandatory
      Status
    }
  }
  Attributes {
    Client
    AppSource
    Carrier
    Lob
    State
    Product
    RaterVersion
    Coverholder
    IsMasterPolicy
    MasterReferenceNumber
    IsTestPolicy
    NoOfClaims
    IsCoverageSaved
    Subjectivity
    UISchemaVersion
    AgentEffectiveDate
    AdjustPremiumType
    AdjustPremiumReason
    AdjustPremiumOtherReason
    CanAgentApproveEnd
    RenewalConfigurations {
      BeforeForAgent {
        Value
        ValueType
      }
      AfterForAgent {
        Value
        ValueType
      }
      BeforeForUnderwriter {
        Value
        ValueType
      }
      AfterForUnderwriter {
        Value
        ValueType
      }
    }
    QuoteValidity {
      Value
      ValueType
    }
  }
  PolicyLog {
    fieldName
    oldValue
    newValue
    Status
    Header
  }
  Audit {
    CreatedBy
    CreatedOn
    LastUpdatedBy
    LastUpdatedOn
  }
  RatingErrors {
    code
    message
    details
  }
  DiscountAndSurcharges {
      Description
  }
  InsuredAccount {
    Type
    CreationDate
    UserName
    FirstName
    MiddleName
    LastName
    DisplayName
    HasJointPolicyHolder
    BankDetails {
      AccountName
      BankName
      BranchName
      AccountType
      RoutingNo
    }
    Communications {
      Type
      SubType
      Value
      Status
    }
    BusinessInfo {
      BusinessType
      YearsInBusiness
      IncorporationAge
      BusinessName
      DisplayName
      RegistrationNumber
      BusinessStruct
      SpecialRisk
      NoOfOwners
      FullTimeEmployees
      PartTimeEmployees
      Website
      IndustryType
      BusinessDecsription
      AnnualRevenue
      NumberOFLocations
      Locations {
        NickName
        LocationNumber
        Type
        IsValid
        Status
        Address {
          IsManual
          StreetName
          AddressLine1
          AddressLine2
          City
          State
          County
          CountyCode
          Zip
          Country
          CountryCode
          PlaceId
          Number
          Name
          Long
          Lat
          Description
          AddressType
          FormattedAddress
          UnFormattedAddress
          Status
          AptSuite
          PoBox
          CityCode
          Territory
          TerritoryCode
        }
      }
    }
    OtherDetails {
      DateOfBirth
      Occupation
      ApplicantEmployerName
      ApplicantEmployerAddress {
        IsManual
        StreetName
        AddressLine1
        AddressLine2
        City
        State
        County
        CountyCode
        Zip
        Country
        CountryCode
        PlaceId
        Number
        Name
        Long
        Lat
        Description
        AddressType
        FormattedAddress
        UnFormattedAddress
        Status
        AptSuite
        PoBox
        CityCode
        Territory
        TerritoryCode
      }
    }
  }
  Rules {
    Action
    MatchingRules{
      Status
      Type
      Description
      Isfulfilled
      Reason
    }
  }
  DisplayRules{
    Reason
    Header
  }
  Forms {
    Status
    FormName
    FormDesc
    Sequence
    FormType
    Template
    IsMandatory
    IsChecked
    AcordCode
    File
    Dmspath
  }
  FeesAndTaxes {
    Code
    Description
    Type
    IsOverride
    Status
    Value
    ValueType
    Amount
    AnnualAmount
    ProductFeesAndTaxes {
      Product
      Code
      Description
      Status
      EffectiveFrom
      RangeFrom
      RangeTo
      IsEarned
      ValueType
      Value        
      DecimalPoints
      RangeValueType
      Transactions
      CalculateOn
      Term
    }
  }
  TransactionFeesAndTaxes {
    Code
    Description
    Type
    IsOverride
    Status
    Value
    ValueType
    Amount
    AnnualAmount
    ProductFeesAndTaxes {
      Product
      Code
      Description
      Status
      EffectiveFrom
      RangeFrom
      RangeTo
      IsEarned
      ValueType
      Value        
      DecimalPoints
      RangeValueType
      Transactions
      CalculateOn
      Term
    }
  }
  ExternalRefrences {
    Id
    ReferenceNumber
    ReferenceTarget
    Status
  }
  PreviousPolicies {
    IsPreviousPolicy
    PreviousPolicyNumber
    OtherCoverages
    IsPreviousClaims
    NoOfClaims
    TotalAmountClaimed
  }
  Risks {
    Properties {
      PropertyAge
      UnitId
      UnitNumber
      Name
      UnitType
      Status
      Premium {
        BasicPremium
        Surcharge
        Discount
        MinPremium
        AnnualPremium
        EffectivePremium
        AnnualPremiumWithFeesAndTaxes
        EffectivePremiumWithFeesAndTaxes
      }
      PremiumFactors {
        Name
        Status
        Type
        Description
        IsApplicable
        IsSelected
        IsMandatory
        Rate      
        Limit
        LimitAmount
        Deductible
        Premium
        EffectivePremium
        PremiumDifference
        Factor {
          Name
          Type
          Description
          Rate    
          Limit
          LimitAmount
          Deductible
          Premium
          EffectivePremium
          IsApplicable
          IsSelected
          IsMandatory
          Status
        }
      }
      Coverages {
        Id
        Name
        Description
        Type
        SettlementType
        Value
        Limit
        LimitAmount
        Deductible
        IsApplicable
        IsSelected
        IsMandatory
        Status
      }
      Audit {
        CreatedBy
        CreatedOn
        LastUpdatedBy
        LastUpdatedOn
      }
      AdditionalParties {
        MortgageeDetails {
          Id
          Status
          Name
          ReferenceNumber
          IsPayee
          PartyType
          InterestType
          CreatedOn
          DeletedOn
          Remark
          Address {
            IsManual
            StreetName
            AddressLine1
            AddressLine2
            City
            State
            County
            CountyCode
            Zip
            Country
            CountryCode
            PlaceId
            Number
            Name
            Long
            Lat
            Description
            AddressType
            FormattedAddress
            UnFormattedAddress
            Status
            AptSuite
            PoBox
            CityCode
            Territory
            TerritoryCode
          }
          Communications {
            Type
            SubType
            Value
            Status
          }
        }
        AdditionalInsured{
          Id
          Status
          Name
          ReferenceNumber
          IsPayee
          PartyType
          InterestType
          CreatedOn
          DeletedOn
          Remark
          Address {
            IsManual
            StreetName
            AddressLine1
            AddressLine2
            City
            State
            County
            CountyCode
            Zip
            Country
            CountryCode
            PlaceId
            Number
            Name
            Long
            Lat
            Description
            AddressType
            FormattedAddress
            UnFormattedAddress
            Status
            AptSuite
            PoBox
            CityCode
            Territory
            TerritoryCode
          }
          Communications {
            Type
            SubType
            Value
            Status
          }
        }
        AdditionalInterest{
          Id
          Status
          Name
          ReferenceNumber
          IsPayee
          PartyType
          InterestType
          CreatedOn
          DeletedOn
          Remark
          Address {
            IsManual
            StreetName
            AddressLine1
            AddressLine2
            City
            State
            County
            CountyCode
            Zip
            Country
            CountryCode
            PlaceId
            Number
            Name
            Long
            Lat
            Description
            AddressType
            FormattedAddress
            UnFormattedAddress
            Status
            AptSuite
            PoBox
            CityCode
            Territory
            TerritoryCode
          }
          Communications {
            Type
            SubType
            Value
            Status
          }
        }
        Trust {
          Id
          Status
          Name
          ReferenceNumber
          IsPayee
          PartyType
          InterestType
          CreatedOn
          DeletedOn
          Remark
          Address {
            IsManual
            StreetName
            AddressLine1
            AddressLine2
            City
            State
            County
            CountyCode
            Zip
            Country
            CountryCode
            PlaceId
            Number
            Name
            Long
            Lat
            Description
            AddressType
            FormattedAddress
            UnFormattedAddress
            Status
            AptSuite
            PoBox
            CityCode
            Territory
            TerritoryCode
          }
          Communications {
            Type
            SubType
            Value
            Status
          }
        }
      }
      PropertyRiskAttributes {
        IsLLC 
        HasSameMailingAddress
        OccupancyType
        CoverageStartDate
        YearBuilt
        SquareFeet
        ConstructionType
        ProtectionClass
        HydrantDistance
        FireStationDistance
        DistanceToTidalWater
        FireStationDriveDuration
        BrushFireDistance
        NoOfStories
        NoOfFamilies
        Foundation
        FireScore
        FireAlarm
        BurglarAlarms
        SprinklerSystem
        ShortTermRental
        WeeksRentedPerYear
        Deadbolt
        FireExtinguisher
        VisibleToNeighbours
        RoofType
        RoofUpdateType
        RoofUpdateYear
        HeatingType
        HeatingUpdateType
        HeatingUpdateYear
        ElectricalType
        ElectricalUpdateType
        ElectricalUpdateYear
        PlumbingType
        PlumbingUpdateType
        PlumbingUpdateYear
        MinimumPremium
        DsValFireScore
        DsValBrushFireDistance
        CovBPercentageOfCovA
        CovCPercentageOfCovA
        CovDPercentageOfCovA
      }
      Address {
        IsManual
        StreetName
        AddressLine1
        AddressLine2
        City
        State
        County
        CountyCode
        Zip
        Country
        CountryCode
        PlaceId
        Number
        Name
        Long
        Lat
        Description
        AddressType
        FormattedAddress
        UnFormattedAddress
        Status
        AptSuite
        PoBox
        CityCode
        Territory
        TerritoryCode
      }
    }
  }
  PriorInsurances {
    IsCurrentlyInsured
    CompanyName
    OtherCompanyName
    EffectiveDate
    ExpirationDate
    Premium
    Status
    LapsesInCoverages
    ReasonLapsesInCoverages
  }
  TransactionHistory {
    Type
    Date
    EffectiveDate
    Number
    Remarks
    EffectivePremium
    AnnualPremium
    EffectivePremiumWithFeesAndTaxes
    AnnualPremiumWithFeesAndTaxes
    UpdatedBy
    UpdatedOn
    AnnualFees
    AnnualTax
    Fees
    Taxes
  }
  AgentCommission {
    Value
    ValueType
  }
  JointPolicyHolders {
    Id
    FirstName
    MiddleName
    LastName
    DateOfBirth
    InsuredType
    Age {
      Value
      ValueType
    }
    Occupation
    IsHighProfile
    IsAddressSameAsRisk
    Address {
      IsManual
      StreetName
      AddressLine1
      AddressLine2
      City
      State
      County
      CountyCode
      Zip
      Country
      CountryCode
      PlaceId
      Number
      Name
      Long
      Lat
      Description
      AddressType
      FormattedAddress
      UnFormattedAddress
      Status
      AptSuite
      PoBox
      CityCode
      Territory
      TerritoryCode
    }
    Communications {
      Type
      SubType
      Value
      Status
    }
    OtherDetails {
      DateOfBirth
      Occupation
      EmployerName
      EmployerAddress {
        IsManual
        StreetName
        AddressLine1
        AddressLine2
        City
        State
        County
        CountyCode
        Zip
        Country
        CountryCode
        PlaceId
        Number
        Name
        Long
        Lat
        Description
        AddressType
        FormattedAddress
        UnFormattedAddress
        Status
        AptSuite
        PoBox
        CityCode
        Territory
        TerritoryCode
      }
    }
  }
  Claims {
    Id
    Status
    ClaimSequence
    IsUnrepairedDamage
    DateofLoss
    PaidAmount
    ReserveAmount
    IncidentType
    CoverageType
    ClaimantName
    UnitId
    Remark
  }
}
`;