const staticItems = {
    Client: "ROTHERT",
    Product: "SDRHHO3OR",
    AllowedStates: ["OR"],
    MasterData: [],
    LOBList: {
        HO3: "HO3",
        DP3:"DP3"
    },
    DefaultCoverage: [
        { 
            Occupancy: 'Primary', 
            Coverages:[
                { Name:'coverageB', value:'10', type:'P', percentof:'coverageA'},
                { Name:'coverageC', value:'50', type:'P', percentof:'coverageA'},
                { Name:'coverageD', value:'20', type:'P', percentof:'coverageA'},
                { Name:'coverageE', value:'100000', type:'V', percentof:''},
                { Name:'coverageF', value:'1000', type:'V', percentof:''},
                { Name:'lossAssessment', value:'1000', type:'V', percentof:''},
                { Name:'ordinanceOrLaw', value:'10', type:'V', percentof:''},
                { Name:'increasedCovC', value:'None', type:'V', percentof:''},
                { Name:'personalInjuryCover', value:'no', type:'V', percentof:''},
                { Name:'specialComputerCoverage', value:'no', type:'V', percentof:''},
                { Name:'replacmentCostContents', value:'no', type:'V', percentof:''},
                { Name:'specialPersonalPropertyCoverage', value:'no', type:'V', percentof:''},
                { Name:'waterBackup', value:'0', type:'V', percentof:''},
                { Name:'extendedReplacementCost', value:'no', type:'V', percentof:''},
                { Name:'identityFraudExp', value:'Excluded', type:'V', percentof:''},
                { Name:'mechanicalBreakDownCoverage', value:'no', type:'V', percentof:''},
                { Name:'allOtherPerils', value:'1000', type:'V', percentof:''},
                { Name:'smokeDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'theftDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'waterDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'windDeductible', value:'Excluded', type:'V', percentof:''}
            ]
        },
        { 
            Occupancy: 'Secondary', 
            Coverages:[
                { Name:'coverageB', value:'10', type:'P', percentof:'coverageA'},
                { Name:'coverageC', value:'50', type:'P', percentof:'coverageA'},
                { Name:'coverageD', value:'20', type:'P', percentof:'coverageA'},
                { Name:'coverageE', value:'100000', type:'V', percentof:''},
                { Name:'coverageF', value:'1000', type:'V', percentof:''},
                { Name:'lossAssessment', value:'1000', type:'V', percentof:''},
                { Name:'ordinanceOrLaw', value:'10', type:'V', percentof:''},
                { Name:'increasedCovC', value:'None', type:'V', percentof:''},
                { Name:'personalInjuryCover', value:'no', type:'V', percentof:''},
                { Name:'specialComputerCoverage', value:'no', type:'V', percentof:''},
                { Name:'replacmentCostContents', value:'no', type:'V', percentof:''},
                { Name:'specialPersonalPropertyCoverage', value:'no', type:'V', percentof:''},
                { Name:'waterBackup', value:'0', type:'V', percentof:''},
                { Name:'extendedReplacementCost', value:'no', type:'V', percentof:''},
                { Name:'identityFraudExp', value:'Excluded', type:'V', percentof:''},
                { Name:'mechanicalBreakDownCoverage', value:'no', type:'V', percentof:''},
                { Name:'perilsDeductible', value:'1000', type:'V', percentof:''},
                { Name:'smokeDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'theftDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'waterDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'windDeductible', value:'Excluded', type:'V', percentof:''}
            ]
        },
        { 
            Occupancy: 'Rental', 
            Coverages:[
                { Name:'coverageB', value:'10', type:'P', percentof:'coverageA'},
                { Name:'coverageC', value:'50', type:'P', percentof:'coverageA'},
                { Name:'coverageD', value:'20', type:'P', percentof:'coverageA'},
                { Name:'coverageE', value:'100000', type:'V', percentof:''},
                { Name:'coverageF', value:'1000', type:'V', percentof:''},
                { Name:'lossAssessment', value:'1000', type:'V', percentof:''},
                { Name:'ordinanceOrLaw', value:'10', type:'V', percentof:''},
                { Name:'increasedCovC', value:'None', type:'V', percentof:''},
                { Name:'personalInjuryCover', value:'no', type:'V', percentof:''},
                { Name:'specialComputerCoverage', value:'no', type:'V', percentof:''},
                { Name:'replacmentCostContents', value:'no', type:'V', percentof:''},
                { Name:'specialPersonalPropertyCoverage', value:'no', type:'V', percentof:''},
                { Name:'waterBackup', value:'0', type:'V', percentof:''},
                { Name:'extendedReplacementCost', value:'no', type:'V', percentof:''},
                { Name:'identityFraudExp', value:'Excluded', type:'V', percentof:''},
                { Name:'mechanicalBreakDownCoverage', value:'no', type:'V', percentof:''},
                { Name:'perilsDeductible', value:'1000', type:'V', percentof:''},
                { Name:'smokeDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'theftDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'waterDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'windDeductible', value:'Excluded', type:'V', percentof:''}
            ]
        },
        { 
            Occupancy: 'Secondary Rental', 
            Coverages:[
                { Name:'coverageB', value:'10', type:'P', percentof:'coverageA'},
                { Name:'coverageC', value:'50', type:'P', percentof:'coverageA'},
                { Name:'coverageD', value:'20', type:'P', percentof:'coverageA'},
                { Name:'coverageE', value:'100000', type:'V', percentof:''},
                { Name:'coverageF', value:'1000', type:'V', percentof:''},
                { Name:'lossAssessment', value:'1000', type:'V', percentof:''},
                { Name:'ordinanceOrLaw', value:'10', type:'V', percentof:''},
                { Name:'increasedCovC', value:'None', type:'V', percentof:''},
                { Name:'personalInjuryCover', value:'no', type:'V', percentof:''},
                { Name:'specialComputerCoverage', value:'no', type:'V', percentof:''},
                { Name:'replacmentCostContents', value:'no', type:'V', percentof:''},
                { Name:'specialPersonalPropertyCoverage', value:'no', type:'V', percentof:''},
                { Name:'waterBackup', value:'0', type:'V', percentof:''},
                { Name:'extendedReplacementCost', value:'no', type:'V', percentof:''},
                { Name:'identityFraudExp', value:'Excluded', type:'V', percentof:''},
                { Name:'mechanicalBreakDownCoverage', value:'no', type:'V', percentof:''},
                { Name:'perilsDeductible', value:'1000', type:'V', percentof:''},
                { Name:'smokeDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'theftDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'waterDeductible', value:'Excluded', type:'V', percentof:''},
                { Name:'windDeductible', value:'Excluded', type:'V', percentof:''}
            ]
        }
    ],
    LOBListShortHand: ["HO3"],
    MastersByContainer: ["underwriter", "agents","agencies"],
    UsersKeys: [
        { storeKey: "underwriter", dataKey: "UnderWriter" },
        { storeKey: "agents", dataKey: "Agent" },
        { storeKey: "agencies", dataKey: "Agencies" }
    ],
    ChartFilters: [
        { tabName: 'policyanalytics', chartName: 'transactionTypeWiseCountDoughnut', chartFilterName: 'TransactionType', chartFilterValueField: 'keyName' },
        { tabName: 'policyanalytics', chartName: 'yearwiseCountBar', chartFilterName: 'transactionyear', chartFilterValueField: 'keyName' },
        { tabName: 'policyanalytics', chartName: 'newRenewelWiseCountDoughnut', chartFilterName: 'ReNewalFlag', chartFilterValueField: 'keyName' },
        { tabName: 'policyanalytics', chartName: 'monthwiseCountBar', chartFilterName: 'TransactionMonth', chartFilterValueField: 'keyName' }
    ],
    FormFactoryTransactionTypes: {
        "Application": "NEW",
        "Quote": "NEW",
        "Endorsement": "END",
        "Cancellation": "CAN",
        "Reinstate": "REI",
        "Policy": "NEW",
        "QuoteOffered": "QUOTE"
    },
    GetAnalyticsDataQuery: `
        SELECT c.Id, c.id, c.PolicyNumber, c.PolicyNumber like '%-%' ? 'RB' :'NB' as ReNewalFlag, 
        c.Transaction.Type as SystemType, c.Transaction.Type as SystemTypeDesc, c.Transaction.Type as TransactionType, 
        c.Transaction.Type as TransactionTypeDesc, c.Attributes.Lob as LobCode, 
        c.Transaction.Type = 'Quote' ? '1' :'0' as Quotes, c.Transaction.Type = 'Application' ? '1' :'0' as Applications, 
        c.Transaction.Type = 'Endorsed' ? '1' :'0' as Endorsed, c.Transaction.Type = 'Policy' ? '1' :'0' as Policies, 
        c.Transaction.Type = 'Cancel' ? '1' :'0' as Cancelled, c.Transaction.Type = 'Expire' ? '1' :'0' as Expired, 
        c.Transaction.Type = 'ReInstate' ? '1' :'0' as ReInstate, c.Transaction.Id as TransactionNo, 
        c.Premium.BasicPremium as UnitPremium, c.Premium.BasicPremium as Premium, c.TotalPremium.AnnualPremiumWithFeesAndTaxes as PolicyPremium, 
        1 as NoOfUnits, c.Transaction.Date as TransDate, SUBSTRING(c.Transaction.Date, 0, 4) as transactionyear, 
        SUBSTRING(c.Transaction.Date, INDEX_OF(c.Transaction.Date, \"-\")+1, 2) as TransactionMonth, 
        CONCAT(SUBSTRING(c.Transaction.Date, 0, 4) ,SUBSTRING(c.Transaction.Date, 
        INDEX_OF(c.Transaction.Date, \"-\")+1, 2)) as TransYearMonth, c.Transaction.EffectiveDate as TransactionEffectiveDate, 
        SUBSTRING(c.Transaction.EffectiveDate, 0, 4) as TransEffYear, SUBSTRING(c.Transaction.EffectiveDate, 
        INDEX_OF(c.Transaction.EffectiveDate, \"-\")+1, 2) as TransEffMonth, CONCAT(SUBSTRING(c.Transaction.EffectiveDate, 0, 4) ,
        SUBSTRING(c.Transaction.EffectiveDate, INDEX_OF(c.Transaction.EffectiveDate, \"-\")+1, 2)) as TransEffYearMonth,
        c.QuoteNumber, c.QuoteDate as QuoteCreationDate, SUBSTRING(c.QuoteDate, 0, 4) as QuoteCreationYear, 
        SUBSTRING(c.QuoteDate, INDEX_OF(c.QuoteDate, \"-\")+1, 2) as QuoteCreationMonth, CONCAT(SUBSTRING(c.QuoteDate, 0, 4) ,
        SUBSTRING(c.QuoteDate, INDEX_OF(c.QuoteDate, \"-\")+1, 2)) as QuoteCreationYearMonth, c.Agent.Name as AgentName, c.Agent.Code as AgentCode, 
        c.Agency.Name as AgencyName,c.Agency.Code as AgencyCode, c.UnderWriter.Name as UnderwriterName, c.UnderWriter.Code as UnderwriterCode, c.InsuredAccount.FirstName as InsuredFirstName, 
        c.InsuredAccount.LastName as InsuredLastName, 'None' AS programtype, 'None' AS programtypedesc, 'None' AS inparkoutpark, 
        'None' AS inparkoutparkdesc, 'None' AS ProtectionClassId, 'None' AS ConstructionTypeId, 'None' AS ConstructionTypeDesc, 
        'None' AS BurglarAlarmTypeId, 'None' AS BurglarAlarmTypeDesc, 'None' AS SwimTramp, 'None' AS SwimTrampDesc, c.EffectiveDate as PEffective, 
        c.InsuredAccount.BusinessInfo.BusinessName AS BusinessName, c.ExpirationDate as PExpiration, SUBSTRING(c.ExpirationDate, 0, 4) as ExpirationDateYear, 
        SUBSTRING(c.ExpirationDate, INDEX_OF(c.ExpirationDate, \"-\")+1, 2) as ExpirationDateMonth, CONCAT(SUBSTRING(c.ExpirationDate, 0, 4) ,
        SUBSTRING(c.ExpirationDate, INDEX_OF(c.ExpirationDate, \"-\")+1, 2)) as ExpirationDateYearMonth, c.BindDate as BindDate, 
        SUBSTRING(c.BindDate, 0, 4) as BindDateYear, SUBSTRING(c.BindDate, INDEX_OF(c.BindDate, \"-\")+1, 2) as BindDateMonth, 
        CONCAT(SUBSTRING(c.BindDate, 0, 4) ,SUBSTRING(c.BindDate, INDEX_OF(c.BindDate, \"-\")+1, 2)) as BindDateYearMonth, 
        c.PolicyStatus as PolicyStatus, 'None' AS LatestRecord, c.Attributes.state as State 
        FROM c`,
    MailingImgPath: '/rothert/images/mailbox.png',
    BusinesPageDataPaths: [
        'InsuredAccount.FirstName',
        'InsuredAccount.MiddleName',
        'InsuredAccount.LastName',
        'InsuredAccount.OtherDetails.DateOfBirth',
        'InsuredAccount.OtherDetails.Occupation',
        'InsuredAccount.OtherDetails.ApplicantEmployerName',
        'InsuredAccount.BusinessInfo.BusinessType',
        'InsuredAccount.BusinessInfo.BusinessName',
        'InsuredAccount.Communications.0.Value',
        'InsuredAccount.Communications.1.Value',
        "JointPolicyHolders.0.FirstName",
        "JointPolicyHolders.0.MiddleName",
        "JointPolicyHolders.0.LastName",
        "JointPolicyHolders.0.OtherDetails.DateOfBirth",
        "JointPolicyHolders.0.OtherDetails.Occupation",
        "JointPolicyHolders.0.OtherDetails.EmployerName",
        "Attributes.Lob",
        "Risks.Properties.0.PropertyRiskAttributes.OccupancyType",
        'PolicyTerm.Value',

        'InsuredAccount.BusinessInfo.Locations.0.Address.UnFormattedAddress',
    ],
    PolicyHolder:[
        {key:"First Name", path:'InsuredAccount.FirstName',type:"bool"},
        {key:"Middle Name", path:'InsuredAccount.MiddleName'},
        {key:"Last Name", path:'InsuredAccount.LastName'},
        {key:"Date of Birth", path:'InsuredAccount.OtherDetails.DateOfBirth',type:"date"},
        {key:"Occupation", path:'InsuredAccount.OtherDetails.Occupation'},
        {key:"Applicant's Employer Name", path:'InsuredAccount.OtherDetails.ApplicantEmployerName'},
        {key:"Type of Business", path:'InsuredAccount.BusinessInfo.BusinessType'},
        {key:"LLC Name", path:'InsuredAccount.BusinessInfo.BusinessName'},
        {key:"Insured Number", path:'InsuredAccount.Communications[0].Value',type:"phone"},
        {key:"Insured Email Address", path:'InsuredAccount.Communications[1].Value'},
        {key:"Mailing address", path:'InsuredAccount.BusinessInfo.Locations[0].Address.UnFormattedAddress'},
        {key:"Secondary Policy Holder First Name", path:'JointPolicyHolders[0].FirstName'},
        {key:"Secondary Policy Holder Middle Name", path:'JointPolicyHolders[0].MiddleName'},
        {key:"Secondary Policy Holder Last Name", path:'JointPolicyHolders[0].LastName'},
        {key:"Secondary Policy Holder Date of Birth", path:'JointPolicyHolders[0].OtherDetails.DateOfBirth',type:"date"},
        {key:"Secondary Policy Holder Employer Name", path:'JointPolicyHolders[0].OtherDetails.EmployerName'},
        {key:"LOB Type", path:'Attributes.Lob'},
        {key:"Occupancy Type", path:'Risks.Properties[0].PropertyRiskAttributes.OccupancyType'},
        {key:"Policy Term", path:'PolicyTerm.Value'},
    ],
    PropertyCharacteristics:[
        {key:"Year Built", path:'Risks.Properties[0].PropertyRiskAttributes.YearBuilt'},
        {key:"Area (Sq. Ft)", path:'Risks.Properties[0].PropertyRiskAttributes.SquareFeet',type:"number"},
        {key:"Construction Type", path:'Risks.Properties[0].PropertyRiskAttributes.ConstructionType'},
        {key:"Protection Class", path:'Risks.Properties[0].PropertyRiskAttributes.ProtectionClass'},
        {key:"Distance to the Hydrant (in Feet)", path:'Risks.Properties[0].PropertyRiskAttributes.HydrantDistance',type:"number"},
        {key:"Fire Station Distance (Miles)", path:'Risks.Properties[0].PropertyRiskAttributes.FireStationDistance',type:"number"},
        {key:"Fire Station Drive Duration (Minutes)", path:'Risks.Properties[0].PropertyRiskAttributes.FireStationDriveDuration',type:"number"},
        {key:"Number of Stories", path:'Risks.Properties[0].PropertyRiskAttributes.NoOfStories',type:"number"},
        {key:"Number of Families", path:'Risks.Properties[0].PropertyRiskAttributes.NoOfFamilies',type:"number"},
        {key:"Foundation", path:'Risks.Properties[0].PropertyRiskAttributes.Foundation'},
        {key:"Fire Score", path:'Risks.Properties[0].PropertyRiskAttributes.FireScore'},
        {key:"Brush Fire Distance (in feet)", path:'Risks.Properties[0].PropertyRiskAttributes.BrushFireDistance',type:"number"},
        {key:"Central Station Fire Alarm", path:'Risks.Properties[0].PropertyRiskAttributes.FireAlarm'},
        {key:"Central Station Burglar Alarm", path:'Risks.Properties[0].PropertyRiskAttributes.BurglarAlarms'},
        {key:"Sprinkler System", path:'Risks.Properties[0].PropertyRiskAttributes.SprinklerSystem'},
        {key:"Distance to tidal water (Miles)", path:'Risks.Properties[0].PropertyRiskAttributes.DistanceToTidalWater',type:"number"},
        {key:"Visible to Neighbours", path:'Risks.Properties[0].PropertyRiskAttributes.VisibleToNeighbours',type:"boolean"},
        {key:"Deadbolt", path:'Risks.Properties[0].PropertyRiskAttributes.Deadbolt',type:"boolean"},
        {key:"Fire Extinguisher", path:'Risks.Properties[0].PropertyRiskAttributes.FireExtinguisher',type:"boolean"},
        {key:"Short Term Rental", path:'Risks.Properties[0].PropertyRiskAttributes.ShortTermRental',type:"boolean"},
        {key:"Max number of weeks rented per year", path:'Risks.Properties[0].PropertyRiskAttributes.WeeksRentedPerYear',type:"number"},
        {key:"Roof Type", path:'Risks.Properties[0].PropertyRiskAttributes.RoofType'},
        {key:"Roof Update Year", path:'Risks.Properties[0].PropertyRiskAttributes.RoofUpdateYear'},
        {key:"Roof Update Type", path:'Risks.Properties[0].PropertyRiskAttributes.RoofUpdateType'},
        {key:"Heating Type", path:'Risks.Properties[0].PropertyRiskAttributes.HeatingType'},
        {key:"Heating Update Year", path:'Risks.Properties[0].PropertyRiskAttributes.HeatingUpdateYear'},
        {key:"Heating Update Type", path:'Risks.Properties[0].PropertyRiskAttributes.HeatingUpdateType'},
        {key:"Electrical Type", path:'Risks.Properties[0].PropertyRiskAttributes.ElectricalType'},
        {key:"Electrical Update Year", path:'Risks.Properties[0].PropertyRiskAttributes.ElectricalUpdateYear'},
        {key:"Electrical Update Type", path:'Risks.Properties[0].PropertyRiskAttributes.ElectricalUpdateType'},
        {key:"Plumbing Type", path:'Risks.Properties[0].PropertyRiskAttributes.PlumbingType'},
        {key:"Plumbing Update Year", path:'Risks.Properties[0].PropertyRiskAttributes.PlumbingUpdateYear'},
        {key:"Plumbing Update Type", path:'Risks.Properties[0].PropertyRiskAttributes.PlumbingUpdateType'}      
    ],
    UnderwritingQuestion:[
        {key:"Any business conducted on premises? (Including farms, day care,  etc.)", path:'Underwriting.IsAnyBusinessOnPremise',type:"boolean"},
        {key:"Any residence employees?", path:'Underwriting.AnyResidenceEmployees',type:"boolean"},
        {key:"I. Number of full time employees", path:'Underwriting.NoOfFullTimeEmployees',type:"number"},
        {key:"II. Number of part time employees", path:'Underwriting.NoOfPartTimeEmployees',type:"number"},
        {key:"Any brush, flooding, forest fire hazard, landslide, etc?", path:'Underwriting.IsPropertyInHazardArea',type:"boolean"},
        {key:"Any other residences owned, occupied or rented?", path:'Underwriting.AnyOtherResidence',type:"boolean"},
        {key:"Any other insurance with this company?", path:'Underwriting.IsAnyOtherInsuranceWithCompany',type:"boolean"},
        {key:"List policy numbers", path:'Underwriting.ListPolicyNumber'},
        {key:"Any coverage declined, cancelled or non-renewed during the last three years?", path:'Underwriting.AnyCoverageHistoryInLastThreeYear',type:"boolean"},
        {key:"Has applicant had any foreclosure, repossession, bankruptcy, judgment or lien procedures filed during the past three years?", path:'Underwriting.HadForeclosureRepossessionOrBankruptcy',type:"boolean"},
        {key:"I. Reason", path:'Underwriting.ReasonForForeclosureRepossessionOrBankruptcy'},
        {key:"II. Status", path:'Underwriting.StatusForForeclosureRepossessionOrBankruptcy',type:"boolean"},
        {key:"Date Closed", path:'Underwriting.DateClosedStatusForForeclosureRepossessionOrBankruptcy',type:"date"},
        {key:"Is applicant delinquent on mortgage or tax payments?", path:'Underwriting.IsApplicantDelinquentOnMortgageOrTaxPayment',type:"boolean"},
        {key:"Animals or exotic pets kept on premises?", path:'Underwriting.IsExoticAnimalOrPet',type:"boolean"},
        {key:"I. Breed", path:'Underwriting.AnimalOrPetBreed'},
        {key:"II. Any animal with a prior bite or attack history?", path:'Underwriting.IsAnimalWithBiteHistory',type:"boolean"},
        {key:"Add Type of Animals", path:'Underwriting.AddTypeOfAnimalBox'},
        {key:"Any lake, pond or dock on premises?", path:'Underwriting.IsLakeOrPondOrDockOnPremises',type:"boolean"},
        {key:"Is property situated on more than five acres?", path:'Underwriting.IsPropertyMoreThanFiveAcres',type:"boolean"},
        {key:"I. No. of acres", path:'Underwriting.NoOfAcres',type:"number"},
        {key:"II. Describe land use", path:'Underwriting.DescribeLandUse'},
        {key:"Other structures on premises? (barns, sheds, etc.)", path:'Underwriting.OtherStructureOnPremise',type:"boolean"},
        {key:"Describe", path:'Underwriting.DescribeStructureOnPremise'},
        {key:"Is building retrofitted for earthquake?", path:'Underwriting.IsBuildingRetrofittedForEarthQuake',type:"boolean"},
        {key:"During the last five (5) years (ten (10) years in RI) has any  applicant or household member been indicted or convicted of any  crime? (In RI, failure to disclose the existence of an arson  conviction is a misdemeanor punishable by a sentence of up to one year of imprisonment.)", path:'Underwriting.IsAnyCriminalHistory',type:"boolean"},
        {key:"Is there any existing fire, water or structural damage?", path:'Underwriting.IsAnyExistingDamages',type:"boolean"},
        {key:"Is building undergoing renovation or reconstruction?", path:'Underwriting.IsUnderRenovationOrReconstruction',type:"boolean"},
        {key:"Contractor Name", path:'Underwriting.ContractorName'},
        {key:"Completion Date", path:'Underwriting.CompletionDate',type:"date"},
        {key:"Completed Value", path:'Underwriting.CompletedValue'},
        {key:"Is house for sale?", path:'Underwriting.IsHouseForSale',type:"boolean"},
        {key:"Is property within 300 ft. of a commercial or non residential property", path:'Underwriting.IsAnyCommercialOrNonResidentialProperty',type:"boolean"},
        {key:"Is there a trampoline on the premises?", path:'Underwriting.IsTrampolineOnPremise',type:"boolean"},
        {key:"Was the structure originally built for other than a private residence and then converted?", path:'Underwriting.IsStructureConverted',type:"boolean"},
        {key:"Any swimming pool on premises?", path:'Underwriting.IsAnySwimingPool',type:"boolean"},
        {key:"Is the pool has approved Fencing?", path:'Underwriting.IsSwimingPoolEnclosed',type:"boolean"},
        {key:"If diving boards are present ?", path:'Underwriting.IsAnyDivingBoardsPresent',type:"boolean"},
        {key:"If Slides are present ?", path:'Underwriting.IsAnySlidesPresent',type:"boolean"},
        {key:"Is the property currently insured?", path:'Underwriting.IsThePropertyCurrentlyInsured',type:"boolean"},
        {key:"Prior Insurance Company", path:'Underwriting.PriorInsuranceCompany'},
        {key:"Policy Number", path:'Underwriting.PriorInsurancePolicyNumber'},
        {key:"Prior Insurance Expiration Date", path:'Underwriting.PriorInsuranceExpirationDate',type:"date"}
    ],
    HomeInsuranceHistory:[
        {key:"Lapses in Coverages (Years)", path:'PriorInsurances.LapsesInCoverages',type: "lapes"},
        {key:"Reason for Lapse in Coverage", path:'PriorInsurances.ReasonLapsesInCoverages'},
        {key:"No. of home Insurance claims in last 3 years", path:'Attributes.NoOfClaims',type: "claims"},
        {
            key:"claims History", 
            path:'Claims',
            children:[  
                        {key:"Date of loss", path:'DateofLoss',type:"date"},
                        {key:"Amount Paid", path:'PaidAmount',type:"numberWithDollar"},
                        {key:"Type of incident", path:'IncidentType'},
                        {key:"Claim Status", path:'Status',type:"status"},
                        {key:"Claim Description", path:'Remark'},
                    ]
        },
    ],
    MortgageeDetails:[
        {
            key:"Mortgagee Details", 
            path:'Risks.Properties[0].AdditionalParties.MortgageeDetails',
            children:[  
                        {key:"Name", path:'Name'},
                        {key:"Loan No", path:'ReferenceNumber'},
                        {key:"Address", path:'Address.UnFormattedAddress'}
                    ]
        },
    ],
    AdditionalInsured:[
        {
            key:"Additional Insured", 
            path:'Risks.Properties[0].AdditionalParties.AdditionalInsured',
            children:[  
                        {key:"Name", path:'Name'},
                        {key:"Address", path:'Address.UnFormattedAddress'},
                        {key:"Explain the Insurable Interest in this Location", path:'Remark'}
                    ]
        },
    ],
    AdditionalInterest:[
        {
            key:"Additional Interest", 
            path:'Risks.Properties[0].AdditionalParties.AdditionalInterest',
            children:[  
                        {key:"Name", path:'Name'},
                        {key:"Address", path:'Address.UnFormattedAddress'},
                        {key:"Explain the Insurable Interest in this Location", path:'Remark'}
                    ]
        },
    ],
    TrustDetails:[
        {
            key:"Trust Details", 
            path:'Risks.Properties[0].AdditionalParties.Trust',
            children:[  
                        {key:"Name", path:'Name'},
                        {key:"Address", path:'Address.UnFormattedAddress'},
                        {key:"Description", path:'Remark'}
                    ]
        },
    ],
    CoverageAndLimits:[
        {key:"Dwelling (Coverage A)", path:'Risks.Properties[0].Coverages[0].Value',type: "numberWithDollar"},
        {key:"Other Structures (Coverage B)", path:'Risks.Properties[0].Coverages[1].Value',type: "numberWithDollar"},
        {key:"Personal Property (Coverage C)", path:'Risks.Properties[0].Coverages[2].Value',type: "numberWithDollar"},
        {key:"Loss of Use (Coverage D)", path:'Risks.Properties[0].Coverages[3].Value',type: "numberWithDollar"},
        {key:"Liability (Coverages E)", path:'Risks.Properties[0].Coverages[4].Value',type: "currency"},
        {key:"Medical Payments (Coverages F)", path:'Risks.Properties[0].Coverages[5].Value',type: "currency"},
        {key:"Loss Assessment", path:'Risks.Properties[0].Coverages[6].Value',type: "currency"},
        {key:"Ordinance OR Law", path:'Risks.Properties[0].Coverages[7].Value',type: "percentage"},
        {key:"Increased Cov C Option", path:'Risks.Properties[0].Coverages[8].Value',type: ""},
        {key:"Personal Injury Cover", path:'Risks.Properties[0].Coverages[9].Value',type: "boolWithPlaceHolder"},
        {key:"Special Computer Coverage", path:'Risks.Properties[0].Coverages[10].Value',type: "boolWithPlaceHolder"},
        {key:"Replacement Cost Contents", path:'Risks.Properties[0].Coverages[11].Value',type: "boolWithPlaceHolder"},
        {key:"Special Personal Property Coverage", path:'Risks.Properties[0].Coverages[12].Value',type: "boolWithPlaceHolder"},
        {key:"Water Back Up", path:'Risks.Properties[0].Coverages[13].Value',type: "currency"},
        {key:"Extended Replacement Cost", path:'Risks.Properties[0].Coverages[14].Value',type: "boolWithPlaceHolder"},
        {key:"Identity fraud Exp", path:'Risks.Properties[0].Coverages[15].Value',type: "currency"},
        {key:"Mechanical Breakdown Coverage", path:'Risks.Properties[0].Coverages[18].Value',type: "boolWithPlaceHolder"},
        {key:"All Other Perils", path:'Risks.Properties[0].Coverages[19].Value',type: "currency"},
        {key:"Smoke Deductible", path:'Risks.Properties[0].Coverages[20].Value',type: "currency"},
        {key:"Theft Deductible", path:'Risks.Properties[0].Coverages[21].Value',type: "currency"},
        {key:"Water Deductible", path:'Risks.Properties[0].Coverages[22].Value',type: "currency"},
        {key:"Wind Deductible", path:'Risks.Properties[0].Coverages[23].Value',type: "currency"}
    ],
    BusinessDetailsKeysLabelMap: {
        FirstName: "First Name",
        MiddleName: "Middle Name",
        LastName: "Last Name",
        DateOfBirth: "Date Of Birth",
        YearsInBusiness: "Business Age (In Years)",
        BusinessName: "Business Name",
        DOTNumber: "DOT Number",
        PreviousPolicyNumber: "Previous Policy Number",
        NoOfClaims: "Number Of Claims Filed In The Last 3 Years",
        TotalAmountClaimed: "Total Amount Of Claims Filed",
        Email: "Email",
        PhNo: "Phone Number",

        BusinessType: "Business Type",

        MotorCarrierNumber: "Motor Carrier #",
  
    },
};

export { staticItems };